Repository teamforus/forus-frontend, pull requests merged in 2019-01, with the labels that each got.

#325 fixes teamforus/forus#653
  src/sources/forus-webshop/pug/tpl/pages/home.pug
Labels: invalid

#334 Release v0.1.6a hotfix
  src/sources/forus-platform/js/angular-1/directives/CsvUploadDirective.js
  src/sources/forus-webshop/js/angular-1/i18n/i18n-en.js
  src/sources/forus-webshop/pug/tpl/pages/home.pug
Labels: enhancement

#335 CSV export: change .csv file extension to .xls #608 and csv upload: r…
  src/sources/forus-platform/js/angular-1/directives/PrevalidatedTableDirective.js
  src/sources/forus-platform/js/angular-1/providers/ApiRequestProvider.js
  src/sources/forus-platform/js/angular-1/services/FundService.js
  src/sources/forus-platform/js/angular-1/services/PrevalidationService.js
  src/sources/forus-platform/pug/tpl/directives/prevalidated-table.pug
  src/sources/forus-webshop/js/angular-1/providers/ApiRequestProvider.js
Labels: help wanted

#345 Release v0.1.7
  src/libs/angular_i18n.js
  src/package-lock.json
  src/package.json
  src/platforms/Dashboards/_DashboardBasePlatform.js
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/directives/ClickOutsideDirective.js
  src/sources/forus-platform/js/angular-1/directives/FormLabelToggleDirective.js
  src/sources/forus-platform/js/angular-1/directives/PrevalidatedTableDirective.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-en.js
  src/sources/forus-platform/js/angular-1/providers/ApiRequestProvider.js
  src/sources/forus-platform/js/angular-1/services/FundService.js
  src/sources/forus-platform/js/angular-1/services/PrevalidationService.js
  src/sources/forus-platform/js/angular-1/services/ProductService.js
  src/sources/forus-platform/pug/layout/includes/header.pug
  src/sources/forus-platform/pug/tpl/directives/form-label-toggle.pug
  src/sources/forus-platform/pug/tpl/directives/fund-card-provider-finances.pug
  src/sources/forus-platform/pug/tpl/directives/fund-card-provider.pug
  src/sources/forus-platform/pug/tpl/directives/menu-sponsor.pug
  src/sources/forus-platform/pug/tpl/directives/prevalidated-table.pug
  src/sources/forus-platform/pug/tpl/directives/product-card.pug
  src/sources/forus-platform/pug/tpl/pages/financial-dashboard.pug
  src/sources/forus-platform/pug/tpl/pages/funds-edit.pug
  src/sources/forus-platform/pug/tpl/pages/organization-providers.pug
  src/sources/forus-platform/pug/tpl/pages/products-edit.pug
  src/sources/forus-platform/pug/tpl/pages/transactions.pug
  src/sources/forus-platform/resources/platform-nijmegen/assets/img/icon-login-type/icon_login-type_email.png
  src/sources/forus-platform/resources/platform-nijmegen/assets/img/icon-login-type/icon_login-type_qr.png
  src/sources/forus-platform/resources/platform-nijmegen/assets/img/landing/identity-avatar.svg
  src/sources/forus-platform/scss/_common/dashboard.scss
  src/sources/forus-platform/scss/nijmegen/landing.scss
  src/sources/forus-platform/scss/nijmegen/style-dashboard-nijmegen.scss
  src/sources/forus-platform/scss/nijmegen/vars.scss
  src/sources/forus-webshop/js/angular-1/components/VoucherComponent.js
  src/sources/forus-webshop/js/angular-1/providers/ApiRequestProvider.js
  src/sources/forus-webshop/pug/markup/voucher.pug
  src/sources/forus-webshop/pug/tpl/directives/block-products.pug
  src/sources/forus-webshop/pug/tpl/modals/modal-offices.pug
  src/sources/forus-webshop/pug/tpl/pages/product.pug
  src/sources/forus-webshop/pug/tpl/pages/voucher.pug
  src/sources/forus-webshop/scss/_common/webshop.scss
  src/sources/sample/scss/style.scss
Labels: enhancement

#359 fix teamforus/forus#615 fund amount css
  src/sources/forus-platform/pug/tpl/directives/fund-card-sponsor.pug
Labels: enhancement

#356 fixed teamforus/forus#641 and teamforus/forus#640 and added skip button to open in me
  src/sources/forus-webshop/js/angular-1/components/Modals/ModalOpenInMeComponent.js
  src/sources/forus-webshop/js/angular-1/i18n/i18n-en.js
  src/sources/forus-webshop/pug/tpl/modals/modal-open-in-me.pug
  src/sources/forus-webshop/pug/tpl/modals/modal-pin-code.pug
  src/sources/forus-webshop/scss/nijmegen/style-webshop-nijmegen.scss
Labels: enhancement

#370 Release v0.1.8
  src/platforms/Webshops/WebshopForusPlatform.js
  src/qdt-env.sample.js
  src/sources/forus-platform/js/angular-1/components/TransactionsComponent.js
  src/sources/forus-platform/js/angular-1/directives/PrevalidatedTableDirective.js
  src/sources/forus-platform/js/angular-1/directives/ProductCardDirective.js
  src/sources/forus-platform/js/angular-1/directives/TooltipDirective.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-en.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/js/angular-1/services/TransactionService.js
  src/sources/forus-platform/pug/tpl/directives/fund-card-sponsor.pug
  src/sources/forus-platform/pug/tpl/directives/landing/navbar.pug
  src/sources/forus-platform/pug/tpl/directives/product-card.pug
  src/sources/forus-platform/pug/tpl/modals/modal-employee-edit.pug
  src/sources/forus-platform/pug/tpl/pages/transactions.pug
  src/sources/forus-platform/scss/_common/dashboard.scss
  src/sources/forus-platform/scss/_common/includes/ie.scss
  src/sources/forus-platform/scss/nijmegen/landing.scss
  src/sources/forus-webshop/js/angular-1/angular-app.js
  src/sources/forus-webshop/js/angular-1/components/KindpakketComponent.js
  src/sources/forus-webshop/js/angular-1/components/MeComponent.js
  src/sources/forus-webshop/js/angular-1/components/Modals/ModalAuthCodeComponent.js
  src/sources/forus-webshop/js/angular-1/components/Modals/ModalOpenInMeComponent.js
  src/sources/forus-webshop/js/angular-1/components/PlatformComponent.js
  src/sources/forus-webshop/js/angular-1/components/PortfolioComponent.js
  src/sources/forus-webshop/js/angular-1/config/flags.js
  src/sources/forus-webshop/js/angular-1/directives/GoogleMapDirective.js
  src/sources/forus-webshop/js/angular-1/directives/ImplementationDirective.js
  src/sources/forus-webshop/js/angular-1/directives/WebshopsDirective.js
  src/sources/forus-webshop/js/angular-1/i18n/i18n-en.js
  src/sources/forus-webshop/js/angular-1/routers/router-transitions.js
  src/sources/forus-webshop/js/angular-1/routers/router.js
  src/sources/forus-webshop/pug/tpl/directives/app-footer.pug
  src/sources/forus-webshop/pug/tpl/directives/implementation.pug
  src/sources/forus-webshop/pug/tpl/directives/top-navbar.pug
  src/sources/forus-webshop/pug/tpl/directives/webshops.pug
  src/sources/forus-webshop/pug/tpl/modals/modal-auth-code.pug
  src/sources/forus-webshop/pug/tpl/modals/modal-open-in-me.pug
  src/sources/forus-webshop/pug/tpl/modals/modal-pin-code.pug
  src/sources/forus-webshop/pug/tpl/pages/forus-platform.pug
  src/sources/forus-webshop/pug/tpl/pages/home.pug
  src/sources/forus-webshop/pug/tpl/pages/kindpakket.pug
  src/sources/forus-webshop/pug/tpl/pages/me.pug
  src/sources/forus-webshop/pug/tpl/pages/portfolio.pug
  src/sources/forus-webshop/pug/tpl/pages/product.pug
  src/sources/forus-webshop/pug/tpl/pages/voucher.pug
  src/sources/forus-webshop/resources/_webshop-common/assets/img/site/me/profiel.png
  src/sources/forus-webshop/resources/_webshop-common/assets/img/site/me/scan.png
  src/sources/forus-webshop/resources/_webshop-common/assets/img/site/me/vouchers.png
  src/sources/forus-webshop/resources/_webshop-common/assets/img/site/platform/general.png
  src/sources/forus-webshop/resources/_webshop-common/assets/img/site/platform/nijmegen.png
  src/sources/forus-webshop/resources/_webshop-common/assets/img/site/platform/zuidhorn.png
  src/sources/forus-webshop/scss/_common/webshop.scss
  src/sources/forus-webshop/scss/nijmegen/style-webshop-nijmegen.scss
  src/sources/forus-webshop/scss/zuidhorn/style-webshop-zuidhorn.scss
Labels: enhancement
