Repository teamforus/forus-frontend, pull requests merged in 2022-12, with the labels that each got.

#2384 Schagen webshop styles update
  src/qdt-env.sample.js
  src/sources/forus-webshop/resources/webshop-schagen/assets/fonts/Century Gothic.ttf
  src/sources/forus-webshop/resources/webshop-schagen/assets/fonts/CenturyGothic.ttf
  src/sources/forus-webshop/resources/webshop-schagen/assets/fonts/GOTHIC.TTF
  src/sources/forus-webshop/resources/webshop-schagen/assets/fonts/GOTHICB.TTF
  src/sources/forus-webshop/resources/webshop-schagen/assets/fonts/GOTHICB0.TTF
  src/sources/forus-webshop/resources/webshop-schagen/assets/fonts/GOTHICBI.TTF
  src/sources/forus-webshop/resources/webshop-schagen/assets/fonts/GOTHICI.TTF
  src/sources/forus-webshop/resources/webshop-schagen/assets/img/logo-hover.svg
  src/sources/forus-webshop/resources/webshop-schagen/assets/img/sprite-map.png
  src/sources/forus-webshop/scss/schagen/includes/shame.scss
  src/sources/forus-webshop/scss/schagen/layout/_header.scss
  src/sources/forus-webshop/scss/schagen/style-webshop-schagen.scss
  src/sources/forus-webshop/scss/schagen/vars.scss
Labels: priority: High

#2365 Hartvanwestbrabant webshop styles update
  src/qdt-env.sample.js
  src/sources/forus-webshop/js/angular-1/i18n/nl/layout/navbar.js
  src/sources/forus-webshop/resources/webshop-hartvanwestbrabant/assets/img/favicon.ico
  src/sources/forus-webshop/resources/webshop-hartvanwestbrabant/assets/img/logo-normal.png
  src/sources/forus-webshop/resources/webshop-hartvanwestbrabant/assets/img/logo-normal.svg
  src/sources/forus-webshop/resources/webshop-hartvanwestbrabant/assets/img/map_pin.png
  src/sources/forus-webshop/resources/webshop-hartvanwestbrabant/assets/img/placeholders/product-large.png
  src/sources/forus-webshop/resources/webshop-hartvanwestbrabant/assets/img/placeholders/product-small.png
  src/sources/forus-webshop/resources/webshop-hartvanwestbrabant/assets/img/placeholders/product-thumbnail.png
  src/sources/forus-webshop/resources/webshop-hartvanwestbrabant/assets/img/sprite-map.png
  src/sources/forus-webshop/scss/hartvanwestbrabant/components/_buttons.scss
  src/sources/forus-webshop/scss/hartvanwestbrabant/includes/shame.scss
  src/sources/forus-webshop/scss/hartvanwestbrabant/layout/_navigation.scss
  src/sources/forus-webshop/scss/hartvanwestbrabant/style-webshop-hartvanwestbrabant.scss
  src/sources/forus-webshop/scss/hartvanwestbrabant/vars.scss
Labels: priority: High

#2375 add flags to webshop sign-up page
  src/qdt-env.sample.js
  src/sources/forus-webshop/pug/tpl/pages/sign-up.pug
Labels: priority: Critical

#2398 Fix style on webshop products page
  src/sources/forus-webshop/scss/_common/sections/blocks/block-products-list.scss
Labels: priority: High

#2386 add implementation blocks link target configuration
  src/sources/forus-platform/js/angular-1/directives/ImplementationBlocksEditorDirective.js
  src/sources/forus-platform/pug/tpl/directives/implementation-blocks-editor.pug
  src/sources/forus-webshop/pug/tpl/directives/cms-blocks.pug
Labels: priority: High

#2403 webshop sign-up page redesign
  src/qdt-env.sample.js
  src/sources/forus-webshop/js/angular-1/angular-app.js
  src/sources/forus-webshop/js/angular-1/components/SignUpComponent.js
  src/sources/forus-webshop/pug/tpl/pages/sign-up.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-sign_up.scss
Labels: priority: Critical

#2407 update some translations for the product reservation modal
  src/sources/forus-webshop/js/angular-1/i18n/nl/modals/modal-product-reserve.js
Labels: priority: High

#2406 add sorting by name for products on the webshop
  src/sources/forus-webshop/js/angular-1/services/ProductService.js
Labels: priority: High

#2401 fund FAQ display very long titles in multiple rows
  src/sources/forus-webshop/scss/_common/sections/faq.scss
Labels: priority: Medium

#2387 Add fund requests sorting
  src/sources/forus-platform/js/angular-1/components/FundRequestsComponent.js
  src/sources/forus-platform/pug/tpl/pages/fund-requests.pug
Labels: priority: Medium

#2404 dashboard voucher details page display amount spent
  src/sources/forus-platform/pug/tpl/pages/vouchers-show.pug
Labels: priority: High

#2395 Fix the back button on partner bsn add modal
  src/sources/forus-platform/js/angular-1/components/Modals/ModalFundAppendRequestRecordComponent.js
Labels: priority: Low

#2405 add organization level flag for displaying transactions to providers
  src/sources/forus-platform/js/angular-1/components/VouchersShowComponent.js
Labels: priority: High

#2415 added translation
  src/sources/forus-webshop/js/angular-1/components/SignUpComponent.js
  src/sources/forus-webshop/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-webshop/js/angular-1/i18n/nl/pages/signup.js
  src/sources/forus-webshop/pug/tpl/directives/top-navbar.pug
  src/sources/forus-webshop/pug/tpl/pages/fund-activate.pug
  src/sources/forus-webshop/pug/tpl/pages/sign-up.pug
  src/sources/forus-webshop/resources/webshop-eemsdelta/assets/img/logo-hover.png
  src/sources/forus-webshop/scss/eemsdelta/includes/shame.scss
  src/sources/forus-webshop/scss/vergoedingen/sections/blocks/block-sign_up.scss
  src/sources/forus-webshop/scss/vergoedingen/style-webshop-vergoedingen.scss
Labels: priority: High
