Repository teamforus/forus-frontend, pull requests merged in 2023-01, with the labels that each got.

#2440 Update fund criterion list on validator request page
  src/sources/forus-platform/js/angular-1/components/FundRequestsShowComponent.js
  src/sources/forus-platform/pug/tpl/pages/fund-requests-show.pug
Labels: priority: Medium

#2354 Update validator fund request UI
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/FundRequestsComponent.js
  src/sources/forus-platform/js/angular-1/components/FundRequestsShowComponent.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/pug/tpl/modals/fund-requests/modal-fund-request-disregard-undo.pug
  src/sources/forus-platform/pug/tpl/pages/fund-requests-show.pug
  src/sources/forus-platform/pug/tpl/pages/fund-requests.pug
  src/sources/forus-platform/scss/_common/components/labels.scss
  src/sources/forus-platform/scss/_common/dashboard.scss
  src/sources/forus-platform/scss/_common/includes/common.scss
Labels: priority: High

#2419 fix the zoom for the dashboard header element
  src/sources/forus-platform/scss/_common/dashboard.scss
Labels: priority: Low

#2420 fix issue with webshop product filters on page change
  src/sources/forus-webshop/js/angular-1/components/ProductsComponent.js
  src/sources/forus-webshop/js/angular-1/components/ProvidersComponent.js
  src/sources/forus-webshop/js/angular-1/routers/router.js
Labels: priority: High

#2421 organization edit fix media upload
  src/sources/forus-platform/js/angular-1/components/OrganizationsEditComponent.js
Labels: priority: Medium

#2438 hide default FAQ description on the explanation page
  src/sources/forus-webshop/pug/tpl/pages/explanation.pug
Labels: priority: High

#2416 add some product details on voucher transaction pages
  src/sources/forus-platform/js/angular-1/directives/VoucherTransactionsDirective.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/transaction.pug.i18n.js
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/transactions.pug.i18n.js
  src/sources/forus-platform/pug/tpl/directives/voucher-transactions.pug
  src/sources/forus-platform/pug/tpl/pages/financial-dashboard.pug
  src/sources/forus-platform/pug/tpl/pages/reservations.pug
  src/sources/forus-platform/pug/tpl/pages/transaction-bulk.pug
  src/sources/forus-platform/pug/tpl/pages/transaction.pug
  src/sources/forus-platform/pug/tpl/pages/transactions.pug
Labels: priority: High

#2425 Make client uid for voucher optional for any assign type
  src/sources/forus-platform/js/angular-1/components/Modals/ModalProductVoucherCreateComponent.js
  src/sources/forus-platform/js/angular-1/components/Modals/ModalVoucherCreateComponent.js
  src/sources/forus-platform/js/angular-1/i18n/nl/modals/modal-product-voucher-create.pug.i18n.js
  src/sources/forus-platform/js/angular-1/i18n/nl/modals/modal-voucher-create.pug.i18n.js
  src/sources/forus-platform/js/angular-1/services/VoucherService.js
  src/sources/forus-platform/pug/tpl/modals/modal-product-voucher-create.pug
  src/sources/forus-platform/pug/tpl/modals/modal-voucher-create.pug
  src/sources/forus-platform/pug/tpl/pages/product-vouchers.pug
  src/sources/forus-platform/pug/tpl/pages/vouchers-show.pug
  src/sources/forus-platform/pug/tpl/pages/vouchers.pug
Labels: priority: High

#2430 Add export employees with roles
  src/sources/forus-backend/js/angular-js/providers/ApiRequestProvider.js
  src/sources/forus-platform/js/angular-1/components/OrganizationEmployeesComponent.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/providers/ApiRequestProvider.js
  src/sources/forus-platform/js/angular-1/services/OrganizationEmployeesService.js
  src/sources/forus-platform/pug/tpl/pages/organization-employees.pug
  src/sources/forus-webshop/js/angular-1/providers/ApiRequestProvider.js
Labels: priority: Low

#2434 allow updating voucher limit multipliers to a fixed amount, add it to…
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/VouchersShowComponent.js
  src/sources/forus-platform/js/angular-1/directives/controls/ControlNumericDirective.js
  src/sources/forus-platform/js/angular-1/directives/controls/templates/control-numeric.pug
  src/sources/forus-platform/js/angular-1/i18n/nl/modals/danger-zone/increase-limit-multiplier.js
  src/sources/forus-platform/pug/tpl/pages/vouchers-show.pug
  src/sources/forus-platform/scss/_common/components/forms.scss
Labels: priority: High

#2400 webshop sign-up provider link and button hide if the page isn't acces…
  src/sources/forus-webshop/js/angular-1/components/ProvidersComponent.js
  src/sources/forus-webshop/js/angular-1/directives/AppFooterDirective.js
  src/sources/forus-webshop/pug/tpl/directives/app-footer.pug
  src/sources/forus-webshop/pug/tpl/pages/providers.pug
  src/sources/forus-webshop/pug/tpl/pages/sign-up-provider.pug
Labels: priority: Low

#2383 dashboard add more details about voucher transactions transfer date
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/transactions.pug.i18n.js
  src/sources/forus-platform/pug/tpl/pages/transaction.pug
  src/sources/forus-platform/pug/tpl/pages/transactions.pug
Labels: priority: Low

#2454 update css styles for Schagen webshop
  src/sources/forus-webshop/scss/schagen/includes/shame.scss
  src/sources/forus-webshop/scss/schagen/layout/_header.scss
  src/sources/forus-webshop/scss/schagen/style-webshop-schagen.scss
  src/sources/forus-webshop/scss/schagen/vars.scss
Labels: priority: High

#2453 update the translation for voucher card description on the webshop
  src/sources/forus-webshop/js/angular-1/i18n/nl/pages/voucher.js
  src/sources/forus-webshop/pug/tpl/pages/voucher.pug
Labels: priority: Low

#2462 Change voucher deactivation modal text
  src/sources/forus-platform/js/angular-1/i18n/nl/modals/modal-voucher-deactivation.pug.i18n.js
Labels: priority: Low

#2435 create provider notifications on product reservation cancel by client…
  src/sources/forus-platform/js/angular-1/components/ReservationsComponent.js
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/system-notifications.pug.i18n.json
  src/sources/forus-platform/pug/tpl/pages/reservations.pug
  src/sources/forus-webshop/js/angular-1/components/ReservationsComponent.js
  src/sources/forus-webshop/js/angular-1/directives/ReservationCardDirective.js
  src/sources/forus-webshop/js/angular-1/i18n/en/directives/reservation-card.js
  src/sources/forus-webshop/js/angular-1/i18n/i18n-en.js
  src/sources/forus-webshop/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-webshop/js/angular-1/i18n/nl/directives/reservation-card.js
  src/sources/forus-webshop/js/angular-1/routers/router.js
  src/sources/forus-webshop/js/angular-1/services/ProductReservationService.js
  src/sources/forus-webshop/pug/tpl/directives/reservation-card.pug
  src/sources/forus-webshop/pug/tpl/pages/reservations.pug
Labels: priority: Medium

#2447 Add source reimbursements to voucher transaction create in sponsor dashboard
  src/sources/forus-platform/js/angular-1/components/Modals/ModalVoucherTransactionComponent.js
  src/sources/forus-platform/js/angular-1/i18n/nl/modals/modal-voucher-transaction.pug.i18n.js
  src/sources/forus-platform/pug/tpl/modals/modal-voucher-transaction.pug
  src/sources/forus-platform/scss/_common/components/forms.scss
Labels: priority: Medium

#2461 signup email label to lowercase
  src/sources/forus-platform/pug/tpl/pages/provider-sign-up.pug
  src/sources/forus-platform/pug/tpl/pages/sponsor-sign-up.pug
  src/sources/forus-platform/pug/tpl/pages/validator-sign-up.pug
  src/sources/forus-platform/scss/_common/dashboard.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-sign_up.scss
Labels: priority: High

#2467 funds list show more button
  src/sources/forus-webshop/js/angular-1/directives/lists/FundItemDirective.js
  src/sources/forus-webshop/pug/tpl/directives/lists/funds/fund-item-list.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-funds-list.scss
Labels: priority: Low

#2458 sponsor dashboard voucher page layout enhancements
  src/sources/forus-platform/pug/tpl/pages/vouchers-show.pug
  src/sources/forus-platform/scss/_common/dashboard.scss
Labels: priority: Medium

#2460 Product details funds info adjustments
  src/qdt-env.sample.js
  src/sources/forus-webshop/js/angular-1/components/ProductComponent.js
  src/sources/forus-webshop/js/angular-1/i18n/en/pages/product.js
  src/sources/forus-webshop/js/angular-1/i18n/nl/pages/product.js
  src/sources/forus-webshop/js/angular-1/services/ProductService.js
  src/sources/forus-webshop/pug/tpl/pages/product.pug
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-funds-overview.svg
  src/sources/forus-webshop/scss/_common/sections/blocks/block-action-card.scss
Labels: priority: High

#2470 fix an issue with product subcategories not being loaded in some cases
  src/sources/forus-webshop/js/angular-1/components/ProductsComponent.js
  src/sources/forus-webshop/js/angular-1/components/ProvidersComponent.js
Labels: priority: Critical

#2471 search results and organizations blocks adjust the size of some inner…
  src/sources/forus-webshop/scss/_common/sections/blocks/block-organizations.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-search-results.scss
Labels: priority: Low

#2459 Add voucher transaction batch
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/Modals/ModalVoucherTransactionsUploadComponent.js
  src/sources/forus-platform/js/angular-1/components/TransactionsComponent.js
  src/sources/forus-platform/js/angular-1/directives/ProgressBarDirective.js
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/transactions.pug.i18n.js
  src/sources/forus-platform/js/angular-1/routers/modals.js
  src/sources/forus-platform/js/angular-1/services/TransactionService.js
  src/sources/forus-platform/pug/tpl/directives/voucher-transactions.pug
  src/sources/forus-platform/pug/tpl/modals/modal-transaction-upload.pug
  src/sources/forus-platform/pug/tpl/pages/transaction-bulk.pug
  src/sources/forus-platform/pug/tpl/pages/transaction.pug
  src/sources/forus-platform/pug/tpl/pages/transactions.pug
Labels: priority: High
