Repository teamforus/forus-frontend, pull requests merged in 2023-06, with the labels that each got.

#2703 add business types filter to financial statistics
  src/sources/forus-platform/js/angular-1/components/FinancialDashboardComponent.js
  src/sources/forus-platform/pug/tpl/pages/financial-dashboard.pug
Labels: priority: Medium

#2743 vergoedingen webshop styles fix some color issues
  src/sources/forus-webshop/scss/vergoedingen/includes/shame.scss
  src/sources/forus-webshop/scss/vergoedingen/sections/blocks/block-navbar-search-results.scss
  src/sources/forus-webshop/scss/vergoedingen/style-webshop-vergoedingen.scss
Labels: priority: High

#2745 add amount available filter for vouchers
  src/sources/forus-platform/js/angular-1/components/VouchersComponent.js
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/vouchers.pug.i18n.js
  src/sources/forus-platform/pug/tpl/pages/vouchers.pug
Labels: priority: Medium

#2746 Add funds available sorting for provider
  src/sources/forus-platform/js/angular-1/directives/ProviderAvailableFundsTableDirective.js
  src/sources/forus-platform/pug/tpl/directives/provider-available-funds-table.pug
Labels: priority: Low

#2717 Remove showOnlyUsedCategories flag from webshop
  src/qdt-env.sample.js
  src/sources/forus-webshop/js/angular-1/components/ProductsComponent.js
  src/sources/forus-webshop/js/angular-1/components/ProvidersComponent.js
  src/sources/forus-webshop/js/angular-1/routers/router.js
Labels: priority: Medium

#2738 WCAG add keyboard accessiblity for more webshop elements
  src/sources/forus-webshop/js/angular-1/components/ExplanationComponent.js
  src/sources/forus-webshop/js/angular-1/components/Modals/ModalShareVoucherComponent.js
  src/sources/forus-webshop/js/angular-1/directives/MobileFooterDirective.js
  src/sources/forus-webshop/js/angular-1/directives/TopNavbarDirective.js
  src/sources/forus-webshop/js/angular-1/modules/select-control/directives/templates/select-control.pug
  src/sources/forus-webshop/js/angular-1/modules/ui-controls/UIControlsModule.js
  src/sources/forus-webshop/js/angular-1/modules/ui-controls/directives/UIControlSearchInputDirective.js
  src/sources/forus-webshop/js/angular-1/modules/ui-controls/directives/templates/ui-control-search-input.pug
  src/sources/forus-webshop/pug/tpl/directives/mobile-footer.pug
  src/sources/forus-webshop/pug/tpl/directives/reservation-card.pug
  src/sources/forus-webshop/pug/tpl/directives/top-navbar.pug
  src/sources/forus-webshop/pug/tpl/modals/modal-share-voucher.pug
  src/sources/forus-webshop/pug/tpl/pages/explanation.pug
  src/sources/forus-webshop/pug/tpl/pages/fund-request.pug
  src/sources/forus-webshop/pug/tpl/pages/fund.pug
  src/sources/forus-webshop/pug/tpl/pages/funds.pug
  src/sources/forus-webshop/pug/tpl/pages/products.pug
  src/sources/forus-webshop/pug/tpl/pages/providers.pug
  src/sources/forus-webshop/pug/tpl/pages/reservations.pug
  src/sources/forus-webshop/pug/tpl/pages/sign-up.pug
  src/sources/forus-webshop/pug/tpl/pages/voucher.pug
  src/sources/forus-webshop/scss/_common/components/_form.scss
  src/sources/forus-webshop/scss/_common/components/_ui-controls.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-sticky-footer.scss
Labels: priority: Medium

#2751 fix vergoedingen navbar auth block styles
  src/sources/forus-webshop/resources/webshop-vergoedingen/assets/img/identity-avatar-hover.svg
  src/sources/forus-webshop/resources/webshop-vergoedingen/assets/img/identity-avatar.svg
  src/sources/forus-webshop/scss/vergoedingen/includes/shame.scss
Labels: priority: High

#2691 add the option for validators to edit fund request records
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/FundRequestsShowComponent.js
  src/sources/forus-platform/js/angular-1/components/Modals/ModalEditRequestRecordComponent.js
  src/sources/forus-platform/js/angular-1/directives/FundRequestRecordAttachmentsDirective.js
  src/sources/forus-platform/js/angular-1/directives/FundRequestRecordClarificationsDirective.js
  src/sources/forus-platform/js/angular-1/directives/FundRequestRecordDirective.js
  src/sources/forus-platform/js/angular-1/directives/FundRequestRecordHistoryDirective.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/routers/modals.js
  src/sources/forus-platform/js/angular-1/services/FundRequestValidatorService.js
  src/sources/forus-platform/pug/tpl/directives/fund-request-record-attachments.pug
  src/sources/forus-platform/pug/tpl/directives/fund-request-record-clarifications.pug
  src/sources/forus-platform/pug/tpl/directives/fund-request-record-history.pug
  src/sources/forus-platform/pug/tpl/directives/fund-request-record.pug
  src/sources/forus-platform/pug/tpl/modals/modal-edit-request-record.pug
  src/sources/forus-platform/pug/tpl/pages/fund-requests-show.pug
  src/sources/forus-platform/scss/_common/components/tables.scss
  src/sources/forus-platform/scss/_common/dashboard.scss
Labels: priority: Medium

#2741 make the product alt text configurable and add a default value
  src/sources/forus-platform/js/angular-1/components/ProductsEditComponent.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/services/ProductService.js
  src/sources/forus-platform/pug/tpl/pages/fund-provider.pug
  src/sources/forus-platform/pug/tpl/pages/products-edit.pug
  src/sources/forus-webshop/js/angular-1/components/HomeComponent.js
  src/sources/forus-webshop/js/angular-1/components/ProductComponent.js
  src/sources/forus-webshop/js/angular-1/components/ProductsComponent.js
  src/sources/forus-webshop/js/angular-1/directives/SearchItemsListDirective.js
  src/sources/forus-webshop/js/angular-1/services/ProductService.js
  src/sources/forus-webshop/pug/tpl/directives/lists/products/product-item-grid.pug
  src/sources/forus-webshop/pug/tpl/directives/lists/products/product-item-list-search.pug
  src/sources/forus-webshop/pug/tpl/directives/lists/products/product-item-list.pug
  src/sources/forus-webshop/pug/tpl/directives/product-card.pug
  src/sources/forus-webshop/pug/tpl/pages/product.pug
Labels: priority: Medium

#2757 use translation for organization logo alternative text
  src/sources/forus-platform/js/angular-1/filters/I18nFilter.js
  src/sources/forus-webshop/js/angular-1/directives/TopNavbarDirective.js
  src/sources/forus-webshop/js/angular-1/filters/I18nFilter.js
  src/sources/forus-webshop/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-webshop/pug/tpl/directives/top-navbar.pug
Labels: priority: Medium

#2753 Fix maximum call stack size error
  src/sources/forus-platform/js/angular-1/directives/EventLogsDirective.js
  src/sources/forus-platform/js/angular-1/directives/VouchersDirective.js
Labels: priority: Medium

#2759 Increase notification timeout
  src/sources/forus-platform/js/angular-1/services/PushNotificationsService.js
  src/sources/forus-webshop/js/angular-1/routers/router.js
  src/sources/forus-webshop/js/angular-1/services/ProductService.js
  src/sources/forus-webshop/js/angular-1/services/PushNotificationsService.js
Labels: priority: Medium

#2760 Add css vars for nav item line
  src/sources/forus-webshop/scss/_common/layout/_navigation.scss
  src/sources/forus-webshop/scss/general/vars.scss
  src/sources/forus-webshop/scss/participatiemunt/includes/shame.scss
  src/sources/forus-webshop/scss/participatiemunt/vars.scss
  src/sources/forus-webshop/scss/schagen/includes/shame.scss
  src/sources/forus-webshop/scss/schagen/vars.scss
  src/sources/forus-webshop/scss/vergoedingen/includes/shame.scss
  src/sources/forus-webshop/scss/vergoedingen/vars.scss
Labels: priority: Low

#2709 Vouchers list add state parameters
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/ProductVouchersComponent.js
  src/sources/forus-platform/js/angular-1/components/VouchersComponent.js
  src/sources/forus-platform/js/angular-1/directives/BlockCardVouchersDirective.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/pug/tpl/directives/block-card-vouchers.pug
  src/sources/forus-platform/pug/tpl/pages/identities-show.pug
  src/sources/forus-platform/pug/tpl/pages/product-vouchers.pug
  src/sources/forus-platform/pug/tpl/pages/vouchers.pug
Labels: priority: Low

#2740 add export for reimbursements & add category and name for providers on declarations
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/Modals/ModalEditReimbursementCategoriesComponent.js
  src/sources/forus-platform/js/angular-1/components/Modals/ModalEditReimbursementCategoryComponent.js
  src/sources/forus-platform/js/angular-1/components/Modals/Reimbursements/ModalReimbursementDetailsEditComponent.js
  src/sources/forus-platform/js/angular-1/components/ReimbursementCategoriesEditComponent.js
  src/sources/forus-platform/js/angular-1/components/ReimbursementsComponent.js
  src/sources/forus-platform/js/angular-1/components/ReimbursementsShowComponent.js
  src/sources/forus-platform/js/angular-1/directives/ReimbursementCategoriesDirective.js
  src/sources/forus-platform/js/angular-1/directives/paginators/PaginatorDirective.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/i18n/nl/modals/danger-zone/remove_reimbursement_category.js
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/reimbursements.pug.i18n.js
  src/sources/forus-platform/js/angular-1/routers/modals.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/js/angular-1/services/ReimbursementCategoryService.js
  src/sources/forus-platform/js/angular-1/services/ReimbursementService.js
  src/sources/forus-platform/js/angular-1/services/ReimbursementsExportService.js
  src/sources/forus-platform/pug/tpl/directives/paginators/paginator.pug
  src/sources/forus-platform/pug/tpl/directives/reimbursement-categories.pug
  src/sources/forus-platform/pug/tpl/modals/modal-add-note.pug
  src/sources/forus-platform/pug/tpl/modals/modal-edit-reimbursement-categories.pug
  src/sources/forus-platform/pug/tpl/modals/modal-edit-reimbursement-category.pug
  src/sources/forus-platform/pug/tpl/modals/modal-export-type-select.pug
  src/sources/forus-platform/pug/tpl/modals/modal-fund-criteria-description.pug
  src/sources/forus-platform/pug/tpl/modals/modal-fund-unsubscribe.pug
  src/sources/forus-platform/pug/tpl/modals/modal-markdown-custom-link.pug
  src/sources/forus-platform/pug/tpl/modals/modal-product-voucher-create.pug
  src/sources/forus-platform/pug/tpl/modals/modal-reservation-create.pug
  src/sources/forus-platform/pug/tpl/modals/modal-transfer-organization-ownership.pug
  src/sources/forus-platform/pug/tpl/modals/modal-voucher-create.pug
  src/sources/forus-platform/pug/tpl/modals/reimbursements/modal-reimbursement-details-edit.pug
  src/sources/forus-platform/pug/tpl/pages/reimbursement-categories-edit.pug
  src/sources/forus-platform/pug/tpl/pages/reimbursements-show.pug
  src/sources/forus-platform/pug/tpl/pages/reimbursements.pug
  src/sources/forus-platform/scss/_common/dashboard.scss
  src/sources/forus-webshop/js/angular-1/directives/paginators/PaginatorDirective.js
  src/sources/forus-webshop/pug/tpl/directives/paginators/paginator.pug
Labels: priority: High

#2768 hide the reimbursement icon of the empty block on the providers map
  src/sources/forus-webshop/pug/tpl/pages/providers.pug
Labels: priority: Low

#2767 apply markdown styles on the Me App webshop page
  src/sources/forus-webshop/pug/tpl/pages/me.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-about-me_app.scss
  src/sources/forus-webshop/scss/groningen/layout/_footer.scss
Labels: priority: High

#2775 validator request record value edit enhancements
  src/sources/forus-platform/js/angular-1/components/FundRequestsShowComponent.js
  src/sources/forus-platform/js/angular-1/components/Modals/ModalEditRequestRecordComponent.js
  src/sources/forus-platform/pug/tpl/modals/modal-edit-request-record.pug
  src/sources/forus-platform/pug/tpl/pages/fund-requests-show.pug
Labels: priority: High

#2780 fund-request-records-value-edit-translations
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/pug/tpl/modals/modal-edit-request-record.pug
Labels: priority: High
