Repository teamforus/forus-frontend, pull requests merged in 2023-04, with the labels that each got.

#2603 remove whitespaces from the iban value on reimbursement form submit
  src/sources/forus-webshop/js/angular-1/components/ReimbursementsEditComponent.js
Labels: priority: Medium

#2617 Add pagination to vouchers on webshop
  src/sources/forus-webshop/js/angular-1/components/VouchersComponent.js
  src/sources/forus-webshop/js/angular-1/routers/router.js
  src/sources/forus-webshop/pug/tpl/pages/vouchers.pug
Labels: priority: Low

#2609 Change redirect tab after provider fund apply
  src/sources/forus-platform/js/angular-1/components/ProviderFundsComponent.js
  src/sources/forus-platform/js/angular-1/directives/ProviderAvailableFundsTableDirective.js
  src/sources/forus-platform/pug/tpl/pages/provider-funds.pug
Labels: priority: Low

#2599 webshop homepage refactor client key check
  src/sources/forus-webshop/pug/tpl/pages/home.pug
Labels: priority: Low

#2625 add fees confirmation checkbox on the fund activation page for IIT fu…
  src/sources/forus-webshop/pug/tpl/pages/fund-activate.pug
  src/sources/forus-webshop/pug/tpl/pages/fund-request.pug
Labels: priority: High

#2597 validator fund requests add no assignment filter
  src/sources/forus-platform/js/angular-1/components/FundRequestsComponent.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/pug/tpl/pages/fund-requests.pug
Labels: priority: Low

#2618 add notes for fund requests as validator
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/FundRequestsShowComponent.js
  src/sources/forus-platform/js/angular-1/components/ReimbursementsShowComponent.js
  src/sources/forus-platform/js/angular-1/directives/blocks/BlockCardNoteDirective.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/i18n/nl/modals/danger-zone/remove-note.js
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/reimbursements.pug.i18n.js
  src/sources/forus-platform/js/angular-1/services/FundRequestValidatorService.js
  src/sources/forus-platform/pug/tpl/directives/blocks/block-card-note.pug
  src/sources/forus-platform/pug/tpl/pages/fund-requests-show.pug
  src/sources/forus-platform/pug/tpl/pages/reimbursements-show.pug
Labels: priority: Low

#2569 Add sepa export
  src/sources/forus-platform/js/angular-1/components/TransactionBulkComponent.js
  src/sources/forus-platform/js/angular-1/services/TransactionBulkService.js
  src/sources/forus-platform/pug/tpl/pages/transaction-bulk.pug
Labels: priority: Medium

#2558 Add notifications for bng connection about expiration
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/controllers/BaseController.js
  src/sources/forus-platform/js/angular-1/directives/AnnouncementsDirective.js
  src/sources/forus-platform/js/angular-1/services/AnnouncementService.js
  src/sources/forus-platform/pug/layout/includes/header.pug
  src/sources/forus-platform/pug/tpl/directives/announcements.pug
  src/sources/forus-platform/pug/tpl/pages/organization-bank-connections.pug
Labels: priority: Medium

#2571 small layout enhancements for the dashboard
  src/sources/forus-platform/pug/tpl/modals/modal-voucher-transaction.pug
  src/sources/forus-platform/scss/_common/dashboard.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-products-list.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/product.scss
Labels: priority: Low

#2635 Master.frontend changes iit
  src/sources/forus-webshop/pug/tpl/pages/fund-activate.pug
  src/sources/forus-webshop/pug/tpl/pages/fund.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-sign_up.scss
  src/sources/forus-webshop/scss/vergoedingen/vars.scss
Labels: priority: High

#2556 small bug fixes on the website
  src/sources/forus-platform/js/angular-1/angular-app-website.js
  src/sources/forus-platform/js/angular-1/controllers/landing/BaseController.js
  src/sources/forus-platform/pug/tpl/directives/website/navbar.pug
Labels: priority: Medium

#2629 add loader for fund request confirm criteria
  src/sources/forus-webshop/js/angular-1/components/FundActivateComponent.js
  src/sources/forus-webshop/pug/tpl/pages/fund-activate.pug
  src/sources/forus-webshop/pug/tpl/pages/fund-request.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-sign_up.scss
Labels: priority: High

#2638 Fix record types for fund criteria edit
  src/sources/forus-platform/js/angular-1/components/FundsEditComponent.js
  src/sources/forus-platform/pug/tpl/pages/funds-edit.pug
Labels: priority: Medium

#2527 fix an issue with fonts being imported twice, remove some unused font…
  src/sources/forus-webshop/pug/layout/includes/head.pug
  src/sources/forus-webshop/scss/_common/includes/fonts.scss
  src/sources/forus-webshop/scss/_common/webshop.scss
  src/sources/forus-webshop/scss/berkelland/style-webshop-berkelland.scss
  src/sources/forus-webshop/scss/berkelland/vars.scss
  src/sources/forus-webshop/scss/ede/style-webshop-ede.scss
  src/sources/forus-webshop/scss/ede/vars.scss
  src/sources/forus-webshop/scss/eemsdelta/style-webshop-eemsdelta.scss
  src/sources/forus-webshop/scss/eemsdelta/vars.scss
  src/sources/forus-webshop/scss/geertruidenberg/style-webshop-geertruidenberg.scss
  src/sources/forus-webshop/scss/geertruidenberg/vars.scss
  src/sources/forus-webshop/scss/general/vars.scss
  src/sources/forus-webshop/scss/groningen/style-webshop-groningen.scss
  src/sources/forus-webshop/scss/groningen/vars.scss
  src/sources/forus-webshop/scss/hartvanwestbrabant/style-webshop-hartvanwestbrabant.scss
  src/sources/forus-webshop/scss/hartvanwestbrabant/vars.scss
  src/sources/forus-webshop/scss/heumen/style-webshop-heumen.scss
  src/sources/forus-webshop/scss/heumen/vars.scss
  src/sources/forus-webshop/scss/kerstpakket/style-webshop-kerstpakket.scss
  src/sources/forus-webshop/scss/kerstpakket/vars.scss
  src/sources/forus-webshop/scss/nijmegen/style-webshop-nijmegen.scss
  src/sources/forus-webshop/scss/nijmegen/vars.scss
  src/sources/forus-webshop/scss/noordoostpolder/style-webshop-noordoostpolder.scss
  src/sources/forus-webshop/scss/noordoostpolder/vars.scss
  src/sources/forus-webshop/scss/oostgelre/style-webshop-oostgelre.scss
  src/sources/forus-webshop/scss/oostgelre/vars.scss
  src/sources/forus-webshop/scss/participatiemunt/style-webshop-participatiemunt.scss
  src/sources/forus-webshop/scss/participatiemunt/vars.scss
  src/sources/forus-webshop/scss/potjeswijzer/vars.scss
  src/sources/forus-webshop/scss/schagen/vars.scss
  src/sources/forus-webshop/scss/vergoedingen/vars.scss
  src/sources/forus-webshop/scss/waalwijk/style-webshop-waalwijk.scss
  src/sources/forus-webshop/scss/waalwijk/vars.scss
  src/sources/forus-webshop/scss/westerkwartier/style-webshop-westerkwartier.scss
  src/sources/forus-webshop/scss/westerkwartier/vars.scss
  src/sources/forus-webshop/scss/winterswijk/style-webshop-winterswijk.scss
  src/sources/forus-webshop/scss/winterswijk/vars.scss
Labels: priority: Medium

#2646 Master.frontend changes iit two
  src/sources/forus-webshop/pug/tpl/pages/fund-activate.pug
  src/sources/forus-webshop/pug/tpl/pages/sign-up.pug
Labels: priority: High
