Repository teamforus/forus-frontend, pull requests merged in 2023-09, with the labels that each got.

#2912 fix error in console from phone-control and fix paste into pincode-co…
  src/sources/forus-platform/js/angular-1/directives/PincodeControlDirective.js
  src/sources/forus-platform/js/angular-1/directives/phone_control/PhoneControlDirective.js
  src/sources/forus-webshop/js/angular-1/directives/PincodeControlDirective.js
  src/sources/forus-webshop/js/angular-1/directives/phone_control/PhoneControlDirective.js
Labels: priority: Medium

#2910 Fix pincode control directive for me app auth
  src/sources/forus-backend/js/angular-js/tpl/components/blocks/auth-2fa.pug
Labels: priority: High

#2911 Epic.react
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/IdentityEmailsComponent.js
  src/sources/forus-platform/js/angular-1/components/Modals/Modal2FASetupComponent.js
  src/sources/forus-platform/js/angular-1/components/Modals/ModalFundAppendRequestRecordComponent.js
  src/sources/forus-platform/js/angular-1/components/ProviderSignUpComponent.js
  src/sources/forus-platform/js/angular-1/components/Security2FAComponent.js
  src/sources/forus-platform/js/angular-1/components/SecuritySessionsComponent.js
  src/sources/forus-platform/js/angular-1/components/SponsorSignUpComponent.js
  src/sources/forus-platform/js/angular-1/components/ValidatorSignUpComponent.js
  src/sources/forus-platform/js/angular-1/directives/FundRequestPersonDirective.js
  src/sources/forus-platform/js/angular-1/directives/phone_control/templates/phone_control.pug
  src/sources/forus-platform/js/angular-1/filters/DurationFilter.js
  src/sources/forus-platform/js/angular-1/filters/DurationLastTimeFilter.js
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/system-notifications.pug.i18n.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/js/angular-1/services/SignUpService.js
  src/sources/forus-platform/pug/tpl/directives/email-provider-link.pug
  src/sources/forus-platform/pug/tpl/modals/fund-requests/modal-fund-request-disregard-undo.pug
  src/sources/forus-platform/pug/tpl/modals/fund-requests/modal-fund-request-disregard.pug
  src/sources/forus-platform/pug/tpl/modals/modal-fund-append-request-record.pug
  src/sources/forus-platform/pug/tpl/pages/preferences/emails.pug
  src/sources/forus-platform/pug/tpl/pages/preferences/notifications.pug
  src/sources/forus-platform/pug/tpl/pages/security/sessions.pug
  src/sources/forus-platform/pug/tpl/pages/validator-sign-up.pug
  src/sources/forus-platform/resources/_platform-common/assets/img/me-logo-react.png
  src/sources/forus-platform/scss/_common/components/forms.scss
  src/sources/forus-platform/scss/_common/components/modals.scss
  src/sources/forus-platform/scss/_common/dashboard.scss
  src/sources/forus-platform/scss/_common/includes/helpers.scss
  src/sources/forus-platform/scss/_common/includes/printables.scss
  src/sources/forus-platform/scss/_common/includes/third-party.scss
  src/sources/forus-platform/scss/_common/landing.scss
  src/sources/forus-platform/scss/_common/modals/modal-photo-upload.scss
  src/sources/forus-platform/scss/_common/select-controls/select-control-organizations.scss
  src/sources/forus-platform/scss/general/style-dashboard-general.scss
  src/sources/forus-platform/scss/general/website/components/modals.scss
  src/sources/forus-webshop/js/angular-1/angular-app.js
  src/sources/forus-webshop/js/angular-1/components/Modals/Modal2FASetupComponent.js
  src/sources/forus-webshop/js/angular-1/components/Security2FAComponent.js
  src/sources/forus-webshop/js/angular-1/directives/phone_control/templates/phone_control.pug
  src/sources/forus-webshop/js/angular-1/filters/DurationFilter.js
  src/sources/forus-webshop/js/angular-1/filters/DurationLastTimeFilter.js
  src/sources/forus-webshop/pug/tpl/pages/security/sessions.pug
  src/sources/forus-webshop/scss/_common/components/_modals.scss
  src/sources/forus-webshop/scss/_common/components/_printables.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/voucher.scss
Labels: priority: Medium

#2904 Remove reservation custom fields toggle
  src/sources/forus-platform/pug/tpl/pages/reservations-settings.pug
Labels: priority: High

#2914 allow webshop provider map scrolling
  src/sources/forus-webshop/pug/tpl/pages/provider.pug
Labels: priority: Medium

#2918 wcag set some elements as headers on several webshop pages
  src/sources/forus-webshop/pug/tpl/directives/lists/funds/fund-item-list-search.pug
  src/sources/forus-webshop/pug/tpl/directives/lists/funds/fund-item-list.pug
  src/sources/forus-webshop/pug/tpl/directives/lists/products/product-item-list-search.pug
  src/sources/forus-webshop/pug/tpl/directives/lists/providers/provider-item-list-search.pug
  src/sources/forus-webshop/pug/tpl/directives/reimbursement-card.pug
  src/sources/forus-webshop/pug/tpl/directives/reimbursement-details.pug
  src/sources/forus-webshop/pug/tpl/directives/reservation-card.pug
  src/sources/forus-webshop/pug/tpl/directives/top-navbar-search.pug
  src/sources/forus-webshop/pug/tpl/directives/voucher-card.pug
  src/sources/forus-webshop/pug/tpl/modals/modal-reimbursement-confirm.pug
  src/sources/forus-webshop/pug/tpl/pages/product.pug
  src/sources/forus-webshop/pug/tpl/pages/reimbursements-edit.pug
  src/sources/forus-webshop/pug/tpl/pages/security/sessions.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-navbar-search.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/product.scss
Labels: priority: Medium

#2917 make list items on the webshop providers page non focusable
  src/sources/forus-webshop/pug/tpl/directives/lists/providers/provider-item-list.pug
Labels: priority: Medium

#2916 add wcag aria-current attribute to the webshop profile menu
  src/sources/forus-webshop/js/angular-1/directives/ProfileMenuDirective.js
  src/sources/forus-webshop/pug/tpl/directives/profile-menu.pug
Labels: priority: Medium

#2931 fix system-notifications.pug.i18n.js export
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/system-notifications.pug.i18n.js
  src/sources/forus-platform/pug/tpl/pages/implementation-notifications.pug
Labels: priority: High

#2900 Add fund requests on webshop for requesters
  src/sources/forus-webshop/js/angular-1/angular-app.js
  src/sources/forus-webshop/js/angular-1/components/FundRequestShowComponent.js
  src/sources/forus-webshop/js/angular-1/components/FundRequestsComponent.js
  src/sources/forus-webshop/js/angular-1/directives/FundRequestCardDirective.js
  src/sources/forus-webshop/js/angular-1/directives/controls/FileUploaderDirective.js
  src/sources/forus-webshop/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-webshop/js/angular-1/i18n/nl/directives/profile-menu.js
  src/sources/forus-webshop/js/angular-1/i18n/nl/pages/fund-requests.js
  src/sources/forus-webshop/js/angular-1/i18n/nl/pages/funds.js
  src/sources/forus-webshop/js/angular-1/routers/router.js
  src/sources/forus-webshop/js/angular-1/services/FundRequestService.js
  src/sources/forus-webshop/js/angular-1/services/FundService.js
  src/sources/forus-webshop/pug/tpl/directives/controls/file-uploader.pug
  src/sources/forus-webshop/pug/tpl/directives/empty-block.pug
  src/sources/forus-webshop/pug/tpl/directives/fund-request-card.pug
  src/sources/forus-webshop/pug/tpl/directives/profile-menu.pug
  src/sources/forus-webshop/pug/tpl/directives/top-navbar.pug
  src/sources/forus-webshop/pug/tpl/pages/fund-request-show.pug
  src/sources/forus-webshop/pug/tpl/pages/fund-requests.pug
  src/sources/forus-webshop/pug/tpl/pages/fund.pug
  src/sources/forus-webshop/pug/tpl/pages/product.pug
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-fund-request.svg
  src/sources/forus-webshop/scss/_common/components/_buttons.scss
  src/sources/forus-webshop/scss/_common/components/_label.scss
  src/sources/forus-webshop/scss/_common/components/card.scss
  src/sources/forus-webshop/scss/_common/includes/common.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-file-uploader.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-fund-request.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-fund-requests.scss
  src/sources/forus-webshop/scss/_common/webshop.scss
Labels: priority: High

#2915 make customizable webshop menu items
  src/qdt-env.sample.js
  src/sources/forus-webshop/js/angular-1/directives/TopNavbarDirective.js
  src/sources/forus-webshop/pug/tpl/directives/top-navbar.pug
  src/sources/forus-webshop/scss/_common/layout/_navigation.scss
  src/sources/forus-webshop/scss/vergoedingen/includes/shame.scss
Labels: priority: High

#2952 fix bundle path for landing
  src/sources/forus-platform/pug/layout/includes/website/scripts.pug
Labels: priority: Critical

#2933 wcag enhancements for share voucher modal
  src/sources/forus-webshop/js/angular-1/i18n/en/pages/voucher.js
  src/sources/forus-webshop/js/angular-1/i18n/nl/pages/voucher.js
  src/sources/forus-webshop/pug/tpl/modals/modal-share-voucher.pug
Labels: priority: High

#2943 wcag adjustments for webshop select controls
  src/sources/forus-webshop/js/angular-1/modules/select-control/directives/templates/select-control-voucher.pug
  src/sources/forus-webshop/js/angular-1/modules/select-control/directives/templates/select-control.pug
Labels: priority: High

#2955 Redirect to emails page if no identity email set on voucher page
  src/sources/forus-webshop/js/angular-1/components/VoucherComponent.js
  src/sources/forus-webshop/js/angular-1/routers/router.js
Labels: priority: Low

#2942 Add external page for external fund
  src/sources/forus-platform/js/angular-1/components/FundsEditComponent.js
  src/sources/forus-platform/js/angular-1/services/FundService.js
  src/sources/forus-platform/pug/tpl/pages/funds-edit.pug
  src/sources/forus-webshop/js/angular-1/components/FundComponent.js
  src/sources/forus-webshop/pug/tpl/pages/fund.pug
Labels: priority: High

#2941 Add flag to hide fund meta on fund detail page on webshop
  src/qdt-env.sample.js
  src/sources/forus-webshop/pug/tpl/pages/fund.pug
Labels: priority: High

#2932 wcag add h headers on some webshop pages
  src/sources/forus-webshop/pug/tpl/modals/modal-product-reserve.pug
  src/sources/forus-webshop/pug/tpl/pages/reimbursements.pug
  src/sources/forus-webshop/pug/tpl/pages/vouchers.pug
Labels: priority: High

#2953 Fix pagination for reservations and reimbursements on webshop
  src/sources/forus-webshop/js/angular-1/components/ReimbursementsComponent.js
  src/sources/forus-webshop/js/angular-1/components/ReservationsComponent.js
Labels: priority: Medium

#2907 Mobile webshop fix overflow issues
  src/sources/forus-webshop/pug/tpl/directives/paginators/paginator.pug
  src/sources/forus-webshop/scss/_common/components/_buttons.scss
  src/sources/forus-webshop/scss/_common/components/table-pagination.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-funds-list.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-organizations.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-provider.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-showcase.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-subsidies-list.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/product.scss
Labels: priority: High
