Repository teamforus/forus-frontend, pull requests merged in 2023-02, with the labels that each got.

#2488 dashboard voucher pages update the displayed format for some date fields
  src/sources/forus-platform/pug/tpl/pages/product-vouchers.pug
  src/sources/forus-platform/pug/tpl/pages/vouchers.pug
Labels: priority: Low

#2463 fund description_short increase limit to 500
  src/sources/forus-platform/pug/tpl/pages/funds-edit.pug
  src/sources/forus-platform/scss/_common/blocks/block-fund.scss
  src/sources/forus-webshop/js/angular-1/directives/lists/FundItemDirective.js
  src/sources/forus-webshop/pug/tpl/directives/lists/funds/fund-item-list.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-funds-list.scss
Labels: priority: Medium

#2513 replaced placeholder images for schagen
  src/sources/forus-webshop/resources/webshop-schagen/assets/img/placeholders/product-large.png
  src/sources/forus-webshop/resources/webshop-schagen/assets/img/placeholders/product-small.png
  src/sources/forus-webshop/resources/webshop-schagen/assets/img/placeholders/product-thumbnail.png
Labels: priority: High

#2507 feature: set budget fund product limits
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/FundProviderProductComponent.js
  src/sources/forus-platform/js/angular-1/components/FundProviderProductSubsidyEditComponent.js
  src/sources/forus-platform/js/angular-1/directives/blocks/BlockEmptyDirective.js
  src/sources/forus-platform/js/angular-1/directives/blocks/FundProviderProductEditorDirective.js
  src/sources/forus-platform/pug/layout/includes/scripts.pug
  src/sources/forus-platform/pug/tpl/directives/blocks/block-empty.pug
  src/sources/forus-platform/pug/tpl/directives/blocks/fund-provider-product-editor.pug
  src/sources/forus-platform/pug/tpl/pages/fund-provider-product-subsidy-edit.pug
  src/sources/forus-platform/pug/tpl/pages/fund-provider-product.pug
  src/sources/forus-platform/scss/_common/blocks/block-danger_zone.scss
  src/sources/forus-platform/scss/_common/components/tables.scss
  src/sources/forus-webshop/pug/layout/includes/scripts.pug
  src/sources/forus-webshop/pug/tpl/pages/product.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/product.scss
Labels: priority: Medium

#2528 Transaction generator enhancements
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/transaction.pug.i18n.js
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/vouchers.pug.i18n.js
  src/sources/forus-platform/pug/tpl/pages/product-vouchers.pug
  src/sources/forus-platform/pug/tpl/pages/vouchers-show.pug
  src/sources/forus-platform/pug/tpl/pages/vouchers.pug
Labels: priority: High

#2532 Apply multiple product vouchers at once by record type
  src/sources/forus-platform/js/angular-1/components/FundsEditComponent.js
  src/sources/forus-platform/js/angular-1/modules/select-control/directives/SelectControlDirective.js
  src/sources/forus-platform/js/angular-1/modules/select-control/directives/templates/select-control.pug
  src/sources/forus-platform/pug/tpl/pages/funds-edit.pug
  src/sources/forus-platform/scss/_common/components/forms.scss
  src/sources/forus-webshop/js/angular-1/modules/select-control/directives/templates/select-control.pug
  src/sources/forus-webshop/pug/tpl/modals/_form.scss
Labels: priority: High
