Repository teamforus/forus-frontend, pull requests merged in 2023-11, with the labels that each got.

#2990 Add toggle fund meta information on webshop
  src/sources/forus-platform/js/angular-1/services/FundService.js
  src/sources/forus-platform/pug/tpl/pages/funds-edit.pug
  src/sources/forus-webshop/pug/tpl/pages/fund.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-fund.scss
Labels: priority: High

#3054 Feature.replace legacy phone control
  src/sources/forus-platform/js/angular-1/angular-app-website.js
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/ProviderSignUpComponent.js
  src/sources/forus-platform/js/angular-1/directives/PhoneControlDirective.js
  src/sources/forus-platform/js/angular-1/directives/phone_control/PhoneControlDirective.js
  src/sources/forus-platform/js/angular-1/filters/PhoneNumberFormatFilter.js
  src/sources/forus-platform/pug/tpl/directives/phone-control.pug
  src/sources/forus-platform/pug/tpl/pages/landing/sign-up.pug
  src/sources/forus-platform/pug/tpl/pages/provider-sign-up.pug
  src/sources/forus-platform/scss/_common/blocks/block-app_download.scss
  src/sources/forus-platform/scss/_common/components/forms.scss
  src/sources/forus-webshop/js/angular-1/angular-app.js
  src/sources/forus-webshop/js/angular-1/components/Modals/ModalOpenInMeComponent.js
  src/sources/forus-webshop/js/angular-1/directives/PhoneControlDirective.js
  src/sources/forus-webshop/js/angular-1/directives/phone_control/PhoneControlDirective.js
  src/sources/forus-webshop/js/angular-1/services/ShareService.js
  src/sources/forus-webshop/pug/tpl/directives/phone-control.pug
  src/sources/forus-webshop/pug/tpl/modals/modal-open-in-me.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-sign_up.scss
Labels: priority: Medium

#3066 Added alt text for search icon
  src/sources/forus-webshop/pug/tpl/directives/top-navbar.pug
Labels: priority: High, scope: tiny

#3063 Fix file type for fund request clarification upload
  src/sources/forus-webshop/pug/tpl/pages/fund-request-show.pug
Labels: priority: High

#2966 rewrite external validators page to table view
  src/sources/forus-platform/js/angular-1/components/ExternalValidatorsComponent.js
  src/sources/forus-platform/js/angular-1/components/Modals/ModalProductVoucherCreateComponent.js
  src/sources/forus-platform/js/angular-1/controllers/BaseController.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/pug/tpl/pages/external-validators.pug
  src/sources/forus-platform/scss/_common/components/tables.scss
  src/sources/forus-platform/scss/_common/includes/common.scss
  src/sources/forus-webshop/js/angular-1/components/FundRequestsComponent.js
  src/sources/forus-webshop/js/angular-1/components/ProductsComponent.js
  src/sources/forus-webshop/js/angular-1/components/ProvidersComponent.js
  src/sources/forus-webshop/js/angular-1/components/SearchResultComponent.js
  src/sources/forus-webshop/js/angular-1/routers/router.js
  src/sources/forus-webshop/js/angular-1/services/ProductService.js
Labels: priority: Medium

#3072 wcag: update disabled button colors
  src/sources/forus-webshop/scss/general/vars.scss
Labels: priority: High

#3094 remove website numbers
  src/sources/forus-platform/pug/tpl/pages/website/platform.pug
Labels: scope: tiny, scope: med

#3030 Add mollie integration for provider
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/MolliePrivacyComponent.js
  src/sources/forus-platform/js/angular-1/components/PaymentMethodsComponent.js
  src/sources/forus-platform/js/angular-1/components/ReservationsSettingsComponent.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/i18n/nl/modals/danger-zone/remove-mollie-connection.js
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/mollie-connection.pug.i18n.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/js/angular-1/services/MollieConnectionService.js
  src/sources/forus-platform/pug/tpl/directives/blocks/sponsor/block-provider-organization-overview.pug
  src/sources/forus-platform/pug/tpl/directives/menu-provider.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-bi-tools.pug
  src/sources/forus-platform/pug/tpl/pages/features/template.pug
  src/sources/forus-platform/pug/tpl/pages/fund-provider.pug
  src/sources/forus-platform/pug/tpl/pages/mollie-privacy.pug
  src/sources/forus-platform/pug/tpl/pages/payment-methods.pug
  src/sources/forus-platform/pug/tpl/pages/reservations-settings.pug
  src/sources/forus-platform/resources/_platform-common/assets/img/menu/icon-payment-methods-active.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/menu/icon-payment-methods-hover.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/menu/icon-payment-methods.svg
  src/sources/forus-platform/resources/platform-general/assets/img/svg/mollie-connection-icon-active.svg
  src/sources/forus-platform/resources/platform-general/assets/img/svg/mollie-connection-icon.svg
  src/sources/forus-platform/resources/platform-general/assets/img/svg/mollie-payment-method-icon-active.svg
  src/sources/forus-platform/resources/platform-general/assets/img/svg/mollie-payment-method-icon.svg
  src/sources/forus-platform/scss/_common/blocks/block-content.scss
  src/sources/forus-platform/scss/_common/blocks/block-payment-connection.scss
  src/sources/forus-platform/scss/_common/components/button-groups.scss
  src/sources/forus-platform/scss/_common/components/buttons.scss
  src/sources/forus-platform/scss/_common/components/forms.scss
  src/sources/forus-platform/scss/_common/dashboard.scss
Labels: priority: High

#3111 Fix search in top navbar on mobile
  src/sources/forus-webshop/js/angular-1/directives/TopNavbarDirective.js
Labels: priority: High

#3035 epic: criteria enhancements
  src/sources/forus-platform/js/angular-1/components/FundRequestsShowComponent.js
  src/sources/forus-platform/js/angular-1/components/Modals/ModalCreatePrevalidationComponent.js
  src/sources/forus-platform/js/angular-1/directives/FundCriteriaEditorDirective.js
  src/sources/forus-platform/js/angular-1/directives/FundCriteriaEditorItemDirective.js
  src/sources/forus-platform/js/angular-1/directives/PrevalidatedTableDirective.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/i18n/nl/components/fund-criteria-editor-item.js
  src/sources/forus-platform/js/angular-1/modules/select-control/directives/SelectControlDirective.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/pug/tpl/directives/fund-criteria-editor-item.pug
  src/sources/forus-platform/pug/tpl/directives/prevalidated-table.pug
  src/sources/forus-platform/pug/tpl/modals/modal-create-prevalidation.pug
  src/sources/forus-platform/pug/tpl/modals/modal-fund-criteria-description.pug
  src/sources/forus-platform/scss/_common/blocks/block-critera-editor.scss
  src/sources/forus-webshop/js/angular-1/components/FundRequestComponent.js
  src/sources/forus-webshop/js/angular-1/i18n/en/pages/fund-request.js
  src/sources/forus-webshop/js/angular-1/i18n/nl/pages/fund-request.js
  src/sources/forus-webshop/js/angular-1/modules/select-control/directives/SelectControlDirective.js
  src/sources/forus-webshop/js/angular-1/services/FundService.js
  src/sources/forus-webshop/pug/tpl/pages/fund-activate.pug
  src/sources/forus-webshop/pug/tpl/pages/fund-request.pug
Labels: priority: Medium

#3000 remove business organization type select feature
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/Modals/ModalAuthComponent.js
  src/sources/forus-platform/js/angular-1/components/Modals/ModalBusinessSelectComponent.js
  src/sources/forus-platform/js/angular-1/directives/landing/LandingAuthDirective.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/i18n/nl/modals/modal-business-add.pug.i18n.js
  src/sources/forus-platform/js/angular-1/routers/modals.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/js/angular-1/services/OrganizationService.js
  src/sources/forus-platform/pug/tpl/modals/modal-business-select.pug
  src/sources/forus-platform/scss/_common/components/modals.scss
Labels: priority: Low

#3123 Remove team block from website
  src/sources/forus-platform/pug/tpl/pages/website/current.pug
Labels: priority: Low, scope: tiny

#3120 update some translations on login screens
  src/sources/forus-webshop/js/angular-1/i18n/nl/modals/modal-auth.js
  src/sources/forus-webshop/pug/tpl/pages/sign-up.pug
Labels: priority: High, scope: tiny
