Repository teamforus/forus-frontend, pull requests merged in 2023-05, with the labels that each got.

#2658 button text changed for specific IIT
  src/sources/forus-webshop/js/angular-1/i18n/nl/pages/funds.js
  src/sources/forus-webshop/pug/tpl/pages/fund.pug
Labels: priority: High

#2619 Social media links
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/ImplementationCmsSocialMediaEditComponent.js
  src/sources/forus-platform/js/angular-1/components/Modals/ModalEditSocialMediaComponent.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/i18n/nl/modals/danger-zone/remove-implementation-social-media.js
  src/sources/forus-platform/js/angular-1/routers/modals.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/js/angular-1/services/ImplementationSocialMediaService.js
  src/sources/forus-platform/pug/tpl/modals/modal-edit-social-media.pug
  src/sources/forus-platform/pug/tpl/pages/implementation-cms-edit.pug
  src/sources/forus-platform/pug/tpl/pages/implementation-cms-social-media-edit.pug
  src/sources/forus-webshop/js/angular-1/directives/AppFooterDirective.js
  src/sources/forus-webshop/js/angular-1/directives/TopNavbarDirective.js
  src/sources/forus-webshop/pug/tpl/directives/app-footer.pug
  src/sources/forus-webshop/pug/tpl/directives/top-navbar.pug
  src/sources/forus-webshop/scss/_common/layout/_footer.scss
  src/sources/forus-webshop/scss/_common/layout/_navigation.scss
  src/sources/forus-webshop/scss/potjeswijzer/vars.scss
Labels: priority: Low

#2655 Increase the size of the map in block map
  src/sources/forus-webshop/scss/_common/sections/blocks/map.scss
Labels: priority: Low

#2674 Add fund provider state on providers page in sponsor dashboard
  src/sources/forus-platform/js/angular-1/components/SponsorProviderOrganizationsComponent.js
  src/sources/forus-platform/pug/tpl/pages/sponsor-provider-organizations.pug
Labels: priority: Medium

#2673 add 'how it works' button in the webshop header
  src/sources/forus-webshop/pug/tpl/pages/home.pug
Labels: priority: Medium

#2683 Fix websop modal scroll css on mobile
  src/sources/forus-webshop/scss/_common/components/_modals.scss
Labels: priority: High

#2690 Fix breadcrumbs on the explanation page
  src/sources/forus-webshop/pug/tpl/pages/explanation.pug
Labels: priority: Medium

#2654 Prevent submit auth form if policy checkbox not checked
  src/sources/forus-webshop/js/angular-1/components/SignUpComponent.js
Labels: priority: Low

#2692 rollback chart.js to v2.9.3
  src/package-lock.json
  src/package.json
Labels: priority: High

#2693 doetegoed webshop adjust the background for cms blocks
  src/sources/forus-webshop/scss/doetegoed/sections/blocks/block-cms.scss
Labels: priority: Medium

#2650 dashboard transactions list add state parameters for filters
  src/sources/forus-platform/js/angular-1/components/TransactionsComponent.js
  src/sources/forus-platform/js/angular-1/routers/router.js
Labels: priority: Low

#2696 mobile-webshop-ehancements-border-removal
  src/sources/forus-webshop/scss/_common/layout/_navigation.scss
Labels: priority: Low

#2695 implementation notifications add message when there are no connected …
  src/sources/forus-platform/js/angular-1/components/ImplementationNotificationsComponent.js
  src/sources/forus-platform/pug/tpl/pages/implementation-notifications.pug
Labels: priority: Low

#2719 sponsor dashboard add missing translation for the app info page
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
Labels: priority: Medium

#2718 WCAG add and adjust webshop page titles
  src/sources/forus-webshop/js/angular-1/components/FundComponent.js
  src/sources/forus-webshop/js/angular-1/components/FundsComponent.js
  src/sources/forus-webshop/js/angular-1/components/ProviderComponent.js
  src/sources/forus-webshop/js/angular-1/components/ReimbursementComponent.js
  src/sources/forus-webshop/js/angular-1/components/ReimbursementsEditComponent.js
  src/sources/forus-webshop/js/angular-1/components/SignUpComponent.js
  src/sources/forus-webshop/js/angular-1/components/VoucherComponent.js
  src/sources/forus-webshop/js/angular-1/i18n/i18n-nl.js
Labels: priority: High
