Repository teamforus/forus-frontend, pull requests merged in 2023-12, with the labels that each got.

#3060 update webshop login screen styles
  src/sources/forus-webshop/pug/tpl/pages/privacy.pug
  src/sources/forus-webshop/pug/tpl/pages/sign-up.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-accessibility.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-sign_up.scss
Labels: priority: Low

#3121 fix cms blocks layout issue
  src/sources/forus-webshop/js/angular-1/directives/CmsBlocksDirective.js
  src/sources/forus-webshop/pug/tpl/directives/cms-blocks.pug
  src/sources/forus-webshop/pug/tpl/pages/home.pug
Labels: priority: Medium, scope: tiny

#3118 Update vouchers export file names
  src/sources/forus-platform/js/angular-1/services/VoucherExportService.js
Labels: priority: Medium

#2967 Sponsor provider organizations table view
  src/sources/forus-platform/js/angular-1/components/SponsorProviderOrganizationsComponent.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/pug/tpl/pages/financial-dashboard.pug
  src/sources/forus-platform/pug/tpl/pages/sponsor-provider-organizations.pug
  src/sources/forus-platform/scss/_common/blocks/block-providers.scss
  src/sources/forus-platform/scss/_common/components/tables.scss
  src/sources/forus-platform/scss/_common/dashboard.scss
Labels: priority: Medium, status: needs_investigation

#2985 Rewrite funds list and fund details pages to table view
  src/sources/forus-platform/js/angular-1/components/FundsShowComponent.js
  src/sources/forus-platform/js/angular-1/components/OrganizationFundsComponent.js
  src/sources/forus-platform/js/angular-1/i18n/en/components/organization-funds.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/i18n/nl/components/organization-funds.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/pug/tpl/directives/blocks/block-empty.pug
  src/sources/forus-platform/pug/tpl/pages/fund-provider.pug
  src/sources/forus-platform/pug/tpl/pages/funds-show.pug
  src/sources/forus-platform/pug/tpl/pages/organization-funds.pug
  src/sources/forus-platform/pug/tpl/pages/transactions.pug
  src/sources/forus-platform/scss/_common/blocks/block-announcements.scss
  src/sources/forus-platform/scss/_common/blocks/block-auth-2fa.scss
  src/sources/forus-platform/scss/_common/blocks/block-critera-editor.scss
  src/sources/forus-platform/scss/_common/blocks/block-export-options.scss
  src/sources/forus-platform/scss/_common/blocks/block-external-validators.scss
  src/sources/forus-platform/scss/_common/blocks/block-faq-editor.scss
  src/sources/forus-platform/scss/_common/blocks/block-features-demo-banner.scss
  src/sources/forus-platform/scss/_common/blocks/block-financial-dashboard.scss
  src/sources/forus-platform/scss/_common/blocks/block-fund.scss
  src/sources/forus-platform/scss/_common/blocks/block-fund_types.scss
  src/sources/forus-platform/scss/_common/blocks/block-funds.scss
  src/sources/forus-platform/scss/_common/blocks/block-implementation-blocks-editor.scss
  src/sources/forus-platform/scss/_common/blocks/block-info-box.scss
  src/sources/forus-platform/scss/_common/blocks/block-mail_preview.scss
  src/sources/forus-platform/scss/_common/blocks/block-markdownable.scss
  src/sources/forus-platform/scss/_common/blocks/block-provider-product.scss
  src/sources/forus-platform/scss/_common/blocks/block-sessions.scss
  src/sources/forus-platform/scss/_common/blocks/block-system-notification-editor.scss
  src/sources/forus-platform/scss/_common/blocks/block-timeframe.scss
  src/sources/forus-platform/scss/_common/components/buttons.scss
  src/sources/forus-platform/scss/_common/components/labels.scss
  src/sources/forus-platform/scss/_common/components/modals.scss
  src/sources/forus-platform/scss/_common/components/tables.scss
  src/sources/forus-platform/scss/_common/dashboard.scss
  src/sources/forus-platform/scss/_common/dropdown/dropdown-actions.scss
  src/sources/forus-platform/scss/general/vars.scss
Labels: priority: Medium, status: waits_feedback_fix

#3002 standardize search and filters across dashboard pages
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/event-logs.pug.i18n.js
  src/sources/forus-platform/pug/tpl/directives/event-logs.pug
  src/sources/forus-platform/pug/tpl/directives/prevalidated-table.pug
  src/sources/forus-platform/pug/tpl/pages/organization-funds.pug
  src/sources/forus-platform/pug/tpl/pages/products.pug
  src/sources/forus-platform/pug/tpl/pages/reimbursements.pug
  src/sources/forus-platform/pug/tpl/pages/sponsor-provider-organizations.pug
  src/sources/forus-platform/pug/tpl/pages/transactions.pug
  src/sources/forus-platform/scss/_common/dashboard.scss
Labels: priority: Low, status: waits_feedback_fix

#2995 Tooltips adjustments
  src/sources/forus-platform/pug/tpl/modals/modal-reservation-create.pug
  src/sources/forus-platform/pug/tpl/pages/fund-backoffice-edit.pug
  src/sources/forus-platform/pug/tpl/pages/implementation-cms-edit.pug
  src/sources/forus-platform/pug/tpl/pages/implementation-cms-page-edit.pug
  src/sources/forus-platform/pug/tpl/pages/products-edit.pug
  src/sources/forus-platform/scss/_common/components/modals.scss
  src/sources/forus-webshop/scss/_common/components/_form.scss
Labels: priority: Low, status: waits_feedback_fix

#3124 Add error message if 2fa code send fail
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/i18n/nl/modals/modal-2fa-setup.js
  src/sources/forus-platform/js/angular-1/services/Identity2FAService.js
  src/sources/forus-webshop/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-webshop/js/angular-1/i18n/nl/modals/modal-2fa-setup.js
  src/sources/forus-webshop/js/angular-1/services/Identity2FAService.js
Labels: priority: Medium

#2997 Change birth date format for product reservation form
  src/sources/forus-webshop/js/angular-1/angular-app.js
  src/sources/forus-webshop/js/angular-1/services/DateService.js
  src/sources/forus-webshop/js/angular-1/services/ProductReservationService.js
  src/sources/forus-webshop/pug/tpl/modals/modal-product-reserve.pug
Labels: priority: Medium

#3143 Add horizontal scrolling and implementation filter to vouchers tables
  src/sources/forus-platform/js/angular-1/components/ProductVouchersComponent.js
  src/sources/forus-platform/js/angular-1/components/VouchersComponent.js
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/product-vouchers.pug.i18n.js
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/vouchers.pug.i18n.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/pug/tpl/pages/product-vouchers.pug
  src/sources/forus-platform/pug/tpl/pages/vouchers.pug
  src/sources/forus-platform/scss/_common/components/tables.scss
  src/sources/forus-platform/scss/_common/includes/helpers.scss
Labels: priority: High

#3153 Check voucher duplicates for each filled fund_id in bulk upload
  src/sources/forus-platform/js/angular-1/components/Modals/ModalVouchersUploadComponent.js
  src/sources/forus-platform/pug/tpl/modals/modal-duplicates-picker.pug
  src/sources/forus-platform/pug/tpl/modals/modal-vouchers-upload.pug
  src/sources/forus-platform/scss/_common/blocks/block-switch-table.scss
  src/sources/forus-platform/scss/_common/dashboard.scss
Labels: priority: High

#3165 show the full name in voucher record details, voucher card styles enh…
  src/sources/forus-webshop/js/angular-1/modules/select-control/directives/templates/select-control-options-voucher.pug
  src/sources/forus-webshop/js/angular-1/modules/select-control/directives/templates/select-control-voucher.pug
  src/sources/forus-webshop/pug/tpl/directives/reservation-card.pug
  src/sources/forus-webshop/pug/tpl/modals/modal-product-reserve.pug
  src/sources/forus-webshop/scss/_common/modals/modal-product-reserve.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-reservations.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/vouchers.scss
Labels: priority: High

#3150 Add horizontal scrolling and implementation filter to vouchers tables
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/Modals/ModalFundSelectComponent.js
  src/sources/forus-platform/js/angular-1/components/Modals/ModalVoucherQrCodeComponent.js
  src/sources/forus-platform/js/angular-1/components/Printables/PrintableVoucherQrCodeComponent.js
  src/sources/forus-platform/js/angular-1/components/ProductVouchersComponent.js
  src/sources/forus-platform/js/angular-1/components/VouchersComponent.js
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/product-vouchers.pug.i18n.js
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/vouchers.pug.i18n.js
  src/sources/forus-platform/js/angular-1/modules/select-control/directives/SelectControlDirective.js
  src/sources/forus-platform/js/angular-1/modules/select-control/directives/SelectControlOptions.js
  src/sources/forus-platform/js/angular-1/modules/select-control/directives/templates/select-control-fund.pug
  src/sources/forus-platform/js/angular-1/modules/select-control/directives/templates/select-control-options-fund.pug
  src/sources/forus-platform/js/angular-1/routers/modals.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/pug/tpl/modals/modal-fund-select.pug
  src/sources/forus-platform/pug/tpl/modals/modal-voucher-create.pug
  src/sources/forus-platform/pug/tpl/pages/product-vouchers.pug
  src/sources/forus-platform/pug/tpl/pages/reimbursements-show.pug
  src/sources/forus-platform/pug/tpl/pages/vouchers.pug
  src/sources/forus-platform/scss/_common/components/buttons.scss
  src/sources/forus-platform/scss/_common/components/tables.scss
  src/sources/forus-platform/scss/_common/dashboard.scss
  src/sources/forus-platform/scss/_common/includes/common.scss
  src/sources/forus-platform/scss/_common/includes/helpers.scss
  src/sources/forus-platform/scss/_common/select-controls/select-control-funds.scss
Labels: priority: High
