Repository teamforus/forus-frontend, pull requests merged in 2023-07, with the labels that each got.

#2798 fix filtering by date for vouchers in the sponsor dashboard
  src/sources/forus-platform/js/angular-1/routers/router.js
Labels: priority: Medium

#2776 product reservation modal change content overflow
  src/sources/forus-webshop/scss/_common/components/_form.scss
  src/sources/forus-webshop/scss/_common/modals/modal-product-reserve.scss
Labels: priority: High

#2694 reimbursement display information about the transaction
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/reimbursements.pug.i18n.js
  src/sources/forus-platform/pug/tpl/directives/transaction-details.pug
  src/sources/forus-platform/pug/tpl/pages/reimbursements-show.pug
  src/sources/forus-platform/pug/tpl/pages/reimbursements.pug
  src/sources/forus-platform/scss/_common/dashboard.scss
  src/sources/forus-webshop/pug/tpl/directives/reimbursement-card.pug
Labels: priority: High

#2777 Add BI connection
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/BIConnectionComponent.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/i18n/nl/modals/danger-zone/recreate-bi-connection.js
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/bi-connection.pug.i18n.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/js/angular-1/services/ClipboardService.js
  src/sources/forus-platform/js/angular-1/services/OrganizationService.js
  src/sources/forus-platform/pug/tpl/directives/menu-sponsor.pug
  src/sources/forus-platform/pug/tpl/pages/bi-connection.pug
  src/sources/forus-platform/resources/_platform-common/assets/img/menu/icon-bi-connection-active.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/menu/icon-bi-connection-hover.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/menu/icon-bi-connection.svg
  src/sources/forus-platform/resources/platform-general/assets/img/svg/bi-connection-icon.svg
  src/sources/forus-platform/scss/_common/blocks/block-bi-info.scss
  src/sources/forus-platform/scss/_common/blocks/block-info-box.scss
  src/sources/forus-platform/scss/_common/components/buttons.scss
  src/sources/forus-platform/scss/_common/components/forms.scss
  src/sources/forus-platform/scss/_common/dashboard.scss
  src/sources/forus-platform/scss/_common/includes/common.scss
Labels: priority: High

#2811 Merge test demo webshop Wadenheuvel
  src/platforms/Webshops/WebshopWadenheuvelPlatform.js
  src/qdt-config.js
  src/sources/forus-webshop/resources/webshop-wadenheuvel/assets/favicon.ico
  src/sources/forus-webshop/resources/webshop-wadenheuvel/assets/img/favicon.ico
  src/sources/forus-webshop/resources/webshop-wadenheuvel/assets/img/logo-normal.png
  src/sources/forus-webshop/resources/webshop-wadenheuvel/assets/img/sprite-map.png
  src/sources/forus-webshop/resources/webshop-wadenheuvel/assets/img/sprite-map22.png
  src/sources/forus-webshop/scss/wadenheuvel/includes/shame.scss
  src/sources/forus-webshop/scss/wadenheuvel/style-webshop-wadenheuvel.scss
  src/sources/forus-webshop/scss/wadenheuvel/vars.scss
Labels: priority: Low

#2706 Added GitHub Pull-Request template
  .github/pull_request_template.md
Labels: priority: Low

#2778 align font on webshops
  src/sources/forus-webshop/pug/tpl/directives/cms-blocks.pug
  src/sources/forus-webshop/pug/tpl/pages/explanation.pug
  src/sources/forus-webshop/pug/tpl/pages/fund.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-fund.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-markdown.scss
  src/sources/forus-webshop/scss/doetegoed/sections/blocks/block-cms.scss
Labels: priority: Medium

#2807 transactions details small enhancements
  src/sources/forus-platform/js/angular-1/directives/TransactionDetailsDirective.js
  src/sources/forus-platform/pug/tpl/directives/transaction-details.pug
  src/sources/forus-platform/pug/tpl/pages/reservation-show.pug
  src/sources/forus-platform/pug/tpl/pages/transaction.pug
Labels: priority: Low

#2747 sync fund action options on product details and fund detail pages
  src/sources/forus-webshop/js/angular-1/components/FundComponent.js
  src/sources/forus-webshop/js/angular-1/components/ProductComponent.js
  src/sources/forus-webshop/js/angular-1/directives/lists/FundItemDirective.js
  src/sources/forus-webshop/js/angular-1/services/FundService.js
  src/sources/forus-webshop/pug/tpl/directives/lists/funds/fund-item-list.pug
  src/sources/forus-webshop/pug/tpl/pages/fund.pug
  src/sources/forus-webshop/pug/tpl/pages/product.pug
Labels: priority: Medium

#2814 Fix voucher filter by date after reload browser
  src/sources/forus-platform/js/angular-1/components/VouchersComponent.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/pug/tpl/pages/vouchers.pug
Labels: priority: Medium

#2766 Wcag search control adjustments
  src/sources/forus-platform/js/angular-1/modules/select-control/directives/SelectControlDirective.js
  src/sources/forus-platform/js/angular-1/modules/select-control/directives/templates/select-control-options.pug
  src/sources/forus-platform/js/angular-1/modules/select-control/directives/templates/select-control-organization.pug
  src/sources/forus-platform/js/angular-1/modules/select-control/directives/templates/select-control.pug
  src/sources/forus-platform/scss/_common/components/forms.scss
  src/sources/forus-webshop/js/angular-1/components/FundRequestComponent.js
  src/sources/forus-webshop/js/angular-1/components/SignUpComponent.js
  src/sources/forus-webshop/js/angular-1/modules/select-control/directives/SelectControlDirective.js
  src/sources/forus-webshop/js/angular-1/modules/select-control/directives/templates/select-control-options-voucher.pug
  src/sources/forus-webshop/js/angular-1/modules/select-control/directives/templates/select-control-options.pug
  src/sources/forus-webshop/js/angular-1/modules/select-control/directives/templates/select-control-voucher.pug
  src/sources/forus-webshop/js/angular-1/modules/select-control/directives/templates/select-control.pug
  src/sources/forus-webshop/js/angular-1/modules/ui-controls/directives/templates/ui-control-search-input.pug
  src/sources/forus-webshop/pug/tpl/pages/fund-request.pug
  src/sources/forus-webshop/pug/tpl/pages/sign-up.pug
  src/sources/forus-webshop/scss/_common/components/_form.scss
  src/sources/forus-webshop/scss/_common/components/_ui-controls.scss
Labels: priority: Medium

#2821 sync fund action options on product details and fund details pages
  src/sources/forus-webshop/js/angular-1/components/FundComponent.js
  src/sources/forus-webshop/js/angular-1/components/ProductComponent.js
  src/sources/forus-webshop/js/angular-1/directives/lists/FundItemDirective.js
  src/sources/forus-webshop/js/angular-1/services/FundService.js
  src/sources/forus-webshop/pug/tpl/directives/lists/funds/fund-item-list.pug
  src/sources/forus-webshop/pug/tpl/pages/fund.pug
  src/sources/forus-webshop/pug/tpl/pages/product.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/product.scss
Labels: priority: High

#2761 Webshop download me app images adjustment
  src/qdt-env.sample.js
  src/sources/forus-platform/pug/layout/includes/footer-markup.pug
  src/sources/forus-platform/pug/tpl/directives/elements/app-links.pug
  src/sources/forus-platform/pug/tpl/modals/modal-2fa-setup.pug
  src/sources/forus-platform/pug/tpl/pages/landing/includes/noordoostpolder/footer.pug
  src/sources/forus-platform/pug/tpl/pages/provider-sign-up.pug
  src/sources/forus-platform/resources/_platform-common/assets/img/icon-app-android copy.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/icon-app-android.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/icon-app-ios copy.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/icon-app-ios.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/icon-app/app-store-android.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/icon-app/app-store-badge.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/icon-app/app-store-ios.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/icon-app/icon-app-android.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/landing/icon-app-android.png
  src/sources/forus-platform/resources/_platform-common/assets/img/landing/icon-app-android.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/landing/icon-app-ios.png
  src/sources/forus-platform/resources/_platform-common/assets/img/landing/icon-app-ios.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/landing/icon-app/icon-app-android.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/landing/icon-app/icon-app-ios.svg
  src/sources/forus-platform/scss/_common/blocks/block-app_download.scss
  src/sources/forus-platform/scss/_common/blocks/block-app_links.scss
  src/sources/forus-platform/scss/_common/landing.scss
  src/sources/forus-webshop/js/angular-1/directives/elements/AppLinksDirective.js
  src/sources/forus-webshop/pug/tpl/directives/app-footer.pug
  src/sources/forus-webshop/pug/tpl/directives/elements/app-links.pug
  src/sources/forus-webshop/pug/tpl/modals/modal-2fa-setup.pug
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-app-android-me.png
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-app-android.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-app-ios-me.png
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-app-ios.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-app/app-store-android-dark.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-app/app-store-android-light.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-app/app-store-badge.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-app/app-store-ios-dark.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-app/app-store-ios-light.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-app/icon-app-android.png
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-app/icon-app-android.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-app/icon-app-ios.png
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-app/icon-app-ios.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-app/play-store-badge.png
  src/sources/forus-webshop/resources/_webshop-common/assets/img/me/icon-app-android.png
  src/sources/forus-webshop/resources/_webshop-common/assets/img/me/icon-app-ios.png
  src/sources/forus-webshop/resources/_webshop-common/assets/img/me/icon-app/app-store-badge.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/me/icon-app/icon-app-android.png
  src/sources/forus-webshop/resources/_webshop-common/assets/img/me/icon-app/icon-app-ios.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/me/icon-app/play-store-badge.png
  src/sources/forus-webshop/resources/webshop-potjeswijzer/assets/img/icon-app/app-store-badge.svg
  src/sources/forus-webshop/resources/webshop-potjeswijzer/assets/img/icon-app/icon-app-android.png
  src/sources/forus-webshop/resources/webshop-potjeswijzer/assets/img/icon-app/icon-app-ios.svg
  src/sources/forus-webshop/resources/webshop-potjeswijzer/assets/img/icon-app/play-store-badge.png
  src/sources/forus-webshop/scss/_common/sections/blocks/block-app_download.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-app_links.scss
  src/sources/forus-webshop/scss/potjeswijzer/layout/_footer.scss
Labels: priority: Medium

#2815 Hide provider with products from webshop
  src/sources/forus-platform/js/angular-1/components/FundProviderComponent.js
  src/sources/forus-platform/js/angular-1/components/SponsorProviderOrganizationComponent.js
  src/sources/forus-platform/js/angular-1/directives/blocks/sponsor/BlockProviderOrganizationOverviewDirective.js
  src/sources/forus-platform/pug/tpl/directives/blocks/sponsor/block-provider-organization-overview.pug
  src/sources/forus-platform/pug/tpl/pages/fund-provider.pug
  src/sources/forus-platform/pug/tpl/pages/products-show.pug
  src/sources/forus-platform/pug/tpl/pages/sponsor-provider-organization.pug
  src/sources/forus-platform/scss/_common/components/tables.scss
  src/sources/forus-platform/scss/_common/dashboard.scss
Labels: priority: High

#2634 improvements for the mobile version of webshop
  src/sources/forus-webshop/js/angular-1/directives/MobileFooterDirective.js
  src/sources/forus-webshop/js/angular-1/directives/TopNavbarDirective.js
  src/sources/forus-webshop/js/angular-1/directives/TopNavbarSearchDirective.js
  src/sources/forus-webshop/js/angular-1/i18n/nl/layout/navbar.js
  src/sources/forus-webshop/pug/tpl/directives/mobile-footer.pug
  src/sources/forus-webshop/pug/tpl/directives/top-navbar-search.pug
  src/sources/forus-webshop/pug/tpl/directives/top-navbar.pug
  src/sources/forus-webshop/scss/_common/includes/shame.scss
  src/sources/forus-webshop/scss/_common/layout/_navigation.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-navbar-search.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-sticky-footer.scss
  src/sources/forus-webshop/scss/berkelland/vars.scss
  src/sources/forus-webshop/scss/doetegoed/layout/_navigation.scss
  src/sources/forus-webshop/scss/ede/vars.scss
  src/sources/forus-webshop/scss/eemsdelta/vars.scss
  src/sources/forus-webshop/scss/geertruidenberg/vars.scss
  src/sources/forus-webshop/scss/general/vars.scss
  src/sources/forus-webshop/scss/groningen/sections/blocks/block-markdown.scss
  src/sources/forus-webshop/scss/groningen/style-webshop-groningen.scss
  src/sources/forus-webshop/scss/groningen/vars.scss
  src/sources/forus-webshop/scss/hartvanwestbrabant/vars.scss
  src/sources/forus-webshop/scss/heumen/vars.scss
  src/sources/forus-webshop/scss/kerstpakket/vars.scss
  src/sources/forus-webshop/scss/oostgelre/vars.scss
  src/sources/forus-webshop/scss/participatiemunt/vars.scss
  src/sources/forus-webshop/scss/potjeswijzer/vars.scss
  src/sources/forus-webshop/scss/schagen/includes/shame.scss
  src/sources/forus-webshop/scss/vergoedingen/includes/shame.scss
  src/sources/forus-webshop/scss/vergoedingen/sections/blocks/block-navbar-search-results.scss
  src/sources/forus-webshop/scss/winterswijk/vars.scss
Labels: priority: Medium

#2675 disable description position settings for external implementation pages
  src/sources/forus-platform/pug/tpl/pages/implementation-cms-page-edit.pug
Labels: priority: Medium

#2834 Don't inherit state parameters when switching organization
  src/sources/forus-platform/js/angular-1/controllers/BaseController.js
Labels: priority: Medium

#2804 update some translations and webshop bookmarked products page enhance…
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/i18n/nl/modals/modal-voucher-create.pug.i18n.js
  src/sources/forus-platform/pug/tpl/modals/modal-voucher-record-edit.pug
  src/sources/forus-webshop/js/angular-1/routers/router.js
  src/sources/forus-webshop/pug/tpl/pages/bookmarked-products.pug
Labels: priority: Low

#2672 add archiving and throttles for product reservations
  src/sources/forus-platform/js/angular-1/components/ReservationsComponent.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/js/angular-1/services/ProductReservationService.js
  src/sources/forus-platform/pug/tpl/pages/reservations.pug
  src/sources/forus-webshop/js/angular-1/components/Modals/ModalProductReserveDetailsComponent.js
Labels: priority: Medium

#2806 make the fund description position configurable on the fund details page
  src/sources/forus-platform/js/angular-1/components/FundsEditComponent.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/services/FundService.js
  src/sources/forus-platform/pug/tpl/pages/funds-edit.pug
  src/sources/forus-webshop/pug/tpl/pages/fund.pug
Labels: priority: Medium
