Repository teamforus/forus-frontend, pull requests merged in 2023-10, with the labels that each got.

#2903 add styles for 2FA on mobile webshop
  src/sources/forus-webshop/js/angular-1/components/Security2FAComponent.js
  src/sources/forus-webshop/pug/tpl/modals/modal-2fa-deactivate.pug
  src/sources/forus-webshop/pug/tpl/modals/modal-2fa-setup.pug
  src/sources/forus-webshop/pug/tpl/pages/auth-2fa.pug
  src/sources/forus-webshop/pug/tpl/pages/security/2fa.pug
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-2fa-phone-connect.svg
  src/sources/forus-webshop/scss/_common/components/_form.scss
  src/sources/forus-webshop/scss/_common/includes/shame.scss
  src/sources/forus-webshop/scss/_common/modals/modal-2fa-setup.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-2fa-restriction.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-auth-2fa.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-sign_up.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/profile.scss
Labels: priority: High

#2961 Add fund requests for requesters on webshop
  src/sources/forus-webshop/js/angular-1/angular-app.js
  src/sources/forus-webshop/js/angular-1/components/FundRequestClarificationComponent.js
  src/sources/forus-webshop/js/angular-1/components/FundRequestShowComponent.js
  src/sources/forus-webshop/js/angular-1/components/FundRequestsComponent.js
  src/sources/forus-webshop/js/angular-1/directives/FundRequestCardDirective.js
  src/sources/forus-webshop/js/angular-1/directives/controls/FileUploaderDirective.js
  src/sources/forus-webshop/js/angular-1/directives/lists/FundItemDirective.js
  src/sources/forus-webshop/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-webshop/js/angular-1/i18n/nl/directives/profile-menu.js
  src/sources/forus-webshop/js/angular-1/i18n/nl/layout/navbar.js
  src/sources/forus-webshop/js/angular-1/i18n/nl/pages/fund-requests.js
  src/sources/forus-webshop/js/angular-1/i18n/nl/pages/funds.js
  src/sources/forus-webshop/js/angular-1/routers/router.js
  src/sources/forus-webshop/js/angular-1/services/FundRequestClarificationService.js
  src/sources/forus-webshop/js/angular-1/services/FundRequestService.js
  src/sources/forus-webshop/js/angular-1/services/FundService.js
  src/sources/forus-webshop/pug/tpl/directives/controls/file-uploader.pug
  src/sources/forus-webshop/pug/tpl/directives/empty-block.pug
  src/sources/forus-webshop/pug/tpl/directives/fund-request-card.pug
  src/sources/forus-webshop/pug/tpl/directives/lists/funds/fund-item-list.pug
  src/sources/forus-webshop/pug/tpl/directives/mobile-menu.pug
  src/sources/forus-webshop/pug/tpl/directives/profile-menu.pug
  src/sources/forus-webshop/pug/tpl/directives/top-navbar.pug
  src/sources/forus-webshop/pug/tpl/pages/fund-request-clarification.pug
  src/sources/forus-webshop/pug/tpl/pages/fund-request-show.pug
  src/sources/forus-webshop/pug/tpl/pages/fund-requests.pug
  src/sources/forus-webshop/pug/tpl/pages/fund.pug
  src/sources/forus-webshop/pug/tpl/pages/product.pug
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-fund-request.svg
  src/sources/forus-webshop/scss/_common/components/_buttons.scss
  src/sources/forus-webshop/scss/_common/components/_label.scss
  src/sources/forus-webshop/scss/_common/components/card.scss
  src/sources/forus-webshop/scss/_common/includes/common.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-file-uploader.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-fund-request.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-fund-requests.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-funds-list.scss
  src/sources/forus-webshop/scss/_common/webshop.scss
Labels: priority: High

#2959 add records to voucher creation and add records export
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/Modals/ModalExportDataSelectComponent.js
  src/sources/forus-platform/js/angular-1/components/Modals/ModalProductVoucherCreateComponent.js
  src/sources/forus-platform/js/angular-1/components/Modals/ModalVoucherCreateComponent.js
  src/sources/forus-platform/js/angular-1/components/VouchersComponent.js
  src/sources/forus-platform/js/angular-1/directives/VoucherRecordsEditorDirective.js
  src/sources/forus-platform/js/angular-1/i18n/nl/modals/modal-export-data-select.pug.i18n.js
  src/sources/forus-platform/js/angular-1/services/VoucherExportService.js
  src/sources/forus-platform/pug/tpl/directives/voucher-records-editor.pug
  src/sources/forus-platform/pug/tpl/modals/modal-export-data-select.pug
  src/sources/forus-platform/pug/tpl/modals/modal-product-voucher-create.pug
  src/sources/forus-platform/pug/tpl/modals/modal-voucher-create.pug
  src/sources/forus-platform/pug/tpl/pages/implementation-cms-edit.pug
  src/sources/forus-platform/pug/tpl/pages/implementation-cms-page-edit.pug
  src/sources/forus-platform/scss/_common/blocks/block-export-options.scss
  src/sources/forus-platform/scss/_common/blocks/block-voucher-records-editor.scss
  src/sources/forus-platform/scss/_common/components/forms.scss
  src/sources/forus-platform/scss/_common/components/modals.scss
  src/sources/forus-platform/scss/_common/dashboard.scss
Labels: priority: High

#2970 Hide the 2fa warning block on the fund details page when logged out
  src/sources/forus-webshop/pug/tpl/pages/fund.pug
Labels: priority: Low

#2971 Declaration details page small fix
  src/sources/forus-webshop/pug/tpl/pages/reimbursement.pug
Labels: priority: Medium

#2974 Drop Productboard API for the feedback feature and replace it with em…
  src/qdt-env.sample.js
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/FeedbackComponent.js
  src/sources/forus-platform/js/angular-1/i18n/en/components/feedback.pug.i18n.js
  src/sources/forus-platform/js/angular-1/i18n/en/i18n-components.js
  src/sources/forus-platform/js/angular-1/i18n/nl/components/feedback.pug.i18n.js
  src/sources/forus-platform/js/angular-1/i18n/nl/i18n-components.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/js/angular-1/services/FeedbackService.js
  src/sources/forus-platform/pug/tpl/directives/menu-sponsor.pug
  src/sources/forus-platform/pug/tpl/pages/feedback.pug
  src/sources/forus-platform/resources/_platform-common/assets/img/feedback-failure.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/feedback-success.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/menu/icon-feedback-active.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/menu/icon-feedback-hover.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/menu/icon-feedback.svg
  src/sources/forus-platform/scss/_common/blocks/block-feedback-result.scss
  src/sources/forus-platform/scss/_common/components/forms.scss
  src/sources/forus-platform/scss/_common/dashboard.scss
Labels: priority: Medium

#2779 add markdown to email signature
  src/sources/forus-platform/js/angular-1/components/ImplementationNotificationsBrandingComponent.js
  src/sources/forus-platform/pug/tpl/pages/implementation-notifications-branding.pug
Labels: priority: Medium

#2975 Add focus in header on webshop
  src/sources/forus-webshop/js/angular-1/components/FundRequestComponent.js
  src/sources/forus-webshop/js/angular-1/directives/SkipLinksDirective.js
  src/sources/forus-webshop/js/angular-1/routers/router-transitions.js
  src/sources/forus-webshop/js/angular-1/services/HelperService.js
  src/sources/forus-webshop/pug/tpl/directives/skip-links.pug
  src/sources/forus-webshop/pug/tpl/pages/fund-activate.pug
  src/sources/forus-webshop/pug/tpl/pages/fund-request.pug
  src/sources/forus-webshop/pug/tpl/pages/sign-up.pug
  src/sources/forus-webshop/scss/_common/components/skiplinks.scss
Labels: priority: High

#2996 Remove 'Regelingen' webshop menu item
  src/sources/forus-platform/resources/_platform-common/assets/img/landing/icon-menu/icon-menu-my-vouchers.svg
  src/sources/forus-webshop/js/angular-1/i18n/nl/layout/navbar.js
  src/sources/forus-webshop/pug/layout/includes/top-navbar.pug
  src/sources/forus-webshop/pug/tpl/directives/top-navbar.pug
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-menu/icon-menu-my-profile2.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-menu/icon-menu-my-vouchers.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-menu/icon-menu-my-vouchers2.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-menu/icon-menu-products2.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/me/icon-menu/icon-menu-my-vouchers.svg
Labels: priority: Low

#3024 add goereeoverflakkee webshop
  src/platforms/Webshops/WebshopGoereeoverflakkeePlatform.js
  src/qdt-config.js
  src/qdt-env.sample.js
  src/sources/forus-webshop/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-webshop/pug/tpl/directives/cms-blocks.pug
  src/sources/forus-webshop/pug/tpl/pages/sign-up.pug
  src/sources/forus-webshop/resources/webshop-goereeoverflakkee/assets/img/favicon.ico
  src/sources/forus-webshop/resources/webshop-goereeoverflakkee/assets/img/logo-hover.svg
  src/sources/forus-webshop/resources/webshop-goereeoverflakkee/assets/img/logo-normal.svg
  src/sources/forus-webshop/resources/webshop-goereeoverflakkee/assets/img/placeholders/product-large.png
  src/sources/forus-webshop/resources/webshop-goereeoverflakkee/assets/img/placeholders/product-small.png
  src/sources/forus-webshop/resources/webshop-goereeoverflakkee/assets/img/placeholders/product-thumbnail.png
  src/sources/forus-webshop/resources/webshop-goereeoverflakkee/assets/img/sprite-map.png
  src/sources/forus-webshop/scss/_common/layout/_footer.scss
  src/sources/forus-webshop/scss/_common/layout/_header.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-sign_up.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/includes/buttons.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/includes/form.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/layout/_header.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/layout/_navigation.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/sections/blocks/block-breadcrumbs.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/sections/blocks/block-cms-funds.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/sections/blocks/block-copyrights.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/sections/blocks/block-footer.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/sections/blocks/block-map.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/sections/blocks/block-markdown.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/sections/blocks/block-mobile-menu.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/sections/blocks/block-navbar-search.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/sections/blocks/block-organizations.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/sections/blocks/block-pane.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/sections/blocks/block-product.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/sections/blocks/block-products-list.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/sections/blocks/block-products.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/sections/blocks/block-profile.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/sections/blocks/block-showcase.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/sections/faq.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/sections/flow.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/style-webshop-goereeoverflakkee.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/vars.scss
Labels: priority: High

#3029 wcag transform some elements into h headers
  src/sources/forus-webshop/pug/tpl/directives/fund-criteria-custom-overview.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-sign_up.scss
Labels: priority: High, scope: tiny

#3032 add aria-expanded to fund list item
  src/sources/forus-webshop/pug/tpl/directives/lists/funds/fund-item-list.pug
Labels: priority: High, scope: tiny

#3034 wcag add button link label field for implementation blocks
  src/sources/forus-platform/js/angular-1/directives/ImplementationBlocksEditorDirective.js
  src/sources/forus-platform/pug/tpl/directives/implementation-blocks-editor.pug
  src/sources/forus-webshop/pug/tpl/directives/cms-blocks.pug
Labels: priority: High

#3036 wcag make some organizations block text visible on mobile
  src/sources/forus-webshop/scss/_common/sections/blocks/block-organizations.scss
Labels: priority: High

#3038 wcag fund list item links optimizations
  src/sources/forus-webshop/pug/tpl/directives/lists/funds/fund-item-grid.pug
  src/sources/forus-webshop/pug/tpl/directives/lists/funds/fund-item-list.pug
  src/sources/forus-webshop/pug/tpl/pages/funds.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-funds-list.scss
Labels: priority: High

#3033 Fix mobile menu keyboard accessibility
  src/sources/forus-webshop/js/angular-1/directives/ScrollBreakerDirective.js
Labels: priority: High

#2983 Replace legacy phone and remove legacy code
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/ProviderSignUpComponent.js
  src/sources/forus-platform/js/angular-1/directives/PhoneControlDirective.js
  src/sources/forus-platform/pug/tpl/directives/phone-control.pug
  src/sources/forus-platform/pug/tpl/pages/landing/sign-up.pug
  src/sources/forus-platform/pug/tpl/pages/provider-sign-up.pug
  src/sources/forus-platform/scss/_common/blocks/block-app_download.scss
  src/sources/forus-platform/scss/_common/components/forms.scss
  src/sources/forus-webshop/js/angular-1/angular-app.js
  src/sources/forus-webshop/js/angular-1/components/Modals/ModalOpenInMeComponent.js
  src/sources/forus-webshop/js/angular-1/directives/PhoneControlDirective.js
  src/sources/forus-webshop/js/angular-1/directives/phone_control/PhoneControlDirective.js
  src/sources/forus-webshop/js/angular-1/services/ShareService.js
  src/sources/forus-webshop/pug/tpl/directives/phone-control.pug
  src/sources/forus-webshop/pug/tpl/modals/modal-open-in-me.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-sign_up.scss
Labels: priority: High

#3050 wcag adjust the attributes of form elements
  src/sources/forus-webshop/pug/tpl/modals/modal-deactivate-voucher.pug
  src/sources/forus-webshop/pug/tpl/modals/modal-product-reserve.pug
  src/sources/forus-webshop/pug/tpl/pages/fund-request.pug
  src/sources/forus-webshop/pug/tpl/pages/preferences/emails.pug
  src/sources/forus-webshop/pug/tpl/pages/products.pug
  src/sources/forus-webshop/pug/tpl/pages/providers.pug
  src/sources/forus-webshop/pug/tpl/pages/reimbursements-edit.pug
  src/sources/forus-webshop/pug/tpl/pages/reservations.pug
  src/sources/forus-webshop/pug/tpl/pages/security/2fa.pug
Labels: priority: High

#3052 fix markdown tables wcag issues
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/directives/MarkdownEditorDirective.js
  src/sources/forus-platform/pug/tpl/directives/elements/system-notification-template-editor.pug
  src/sources/forus-platform/pug/tpl/directives/faq-editor.pug
  src/sources/forus-platform/pug/tpl/directives/implementation-blocks-editor.pug
  src/sources/forus-platform/pug/tpl/directives/markdown-editor.pug
  src/sources/forus-platform/pug/tpl/modals/modal-fund-criteria-description.pug
  src/sources/forus-platform/pug/tpl/pages/funds-edit.pug
  src/sources/forus-platform/pug/tpl/pages/implementation-cms-edit.pug
  src/sources/forus-platform/pug/tpl/pages/implementation-cms-page-edit.pug
  src/sources/forus-platform/pug/tpl/pages/implementation-notifications-branding.pug
  src/sources/forus-platform/pug/tpl/pages/organizations-edit.pug
  src/sources/forus-platform/pug/tpl/pages/products-edit.pug
  src/sources/forus-webshop/js/angular-1/angular-app.js
  src/sources/forus-webshop/js/angular-1/directives/MarkdownDirective.js
  src/sources/forus-webshop/pug/tpl/directives/announcements.pug
  src/sources/forus-webshop/pug/tpl/directives/cms-blocks.pug
  src/sources/forus-webshop/pug/tpl/directives/markdown.pug
  src/sources/forus-webshop/pug/tpl/pages/explanation.pug
  src/sources/forus-webshop/pug/tpl/pages/fund-request-show.pug
  src/sources/forus-webshop/pug/tpl/pages/fund-request.pug
  src/sources/forus-webshop/pug/tpl/pages/fund.pug
  src/sources/forus-webshop/pug/tpl/pages/home.pug
  src/sources/forus-webshop/pug/tpl/pages/product.pug
  src/sources/forus-webshop/pug/tpl/pages/provider.pug
  src/sources/forus-webshop/pug/tpl/pages/sign-up-provider.pug
  src/sources/forus-webshop/pug/tpl/pages/voucher.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-markdown.scss
Labels: priority: High

#3053 breadcrumbs fixes and refactoring
  src/platforms/Dashboards/DashboardNijmegenProviderPlatform.js
  src/platforms/Dashboards/DashboardNijmegenSponsorPlatform.js
  src/platforms/Dashboards/DashboardNijmegenValidatorPlatform.js
  src/platforms/Dashboards/DashboardNoordoostpolderProviderPlatform.js
  src/platforms/Dashboards/DashboardNoordoostpolderSponsorPlatform.js
  src/platforms/Dashboards/DashboardOostGelreProviderPlatform.js
  src/platforms/Dashboards/DashboardOostGelreSponsorPlatform.js
  src/platforms/Dashboards/DashboardWesterkwartierProviderPlatform.js
  src/platforms/Dashboards/DashboardWesterkwartierSponsorPlatform.js
  src/platforms/Dashboards/DashboardWinterswijkProviderPlatform.js
  src/platforms/Dashboards/DashboardWinterswijkSponsorPlatform.js
  src/platforms/Dashboards/DashboardZuidhornProviderPlatform.js
  src/platforms/Dashboards/DashboardZuidhornSponsorPlatform.js
  src/sources/forus-webshop/scss/_common/components/_breadcrumbs.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-office.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-provider.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-showcase.scss
  src/sources/forus-webshop/scss/berkelland/components/_breadcrumbs.scss
  src/sources/forus-webshop/scss/berkelland/style-webshop-berkelland.scss
  src/sources/forus-webshop/scss/berkelland/vars.scss
  src/sources/forus-webshop/scss/doetegoed/includes/fonts.scss
  src/sources/forus-webshop/scss/doetegoed/style-webshop-doetegoed.scss
  src/sources/forus-webshop/scss/doetegoed/vars.scss
  src/sources/forus-webshop/scss/ede/style-webshop-ede.scss
  src/sources/forus-webshop/scss/ede/vars.scss
  src/sources/forus-webshop/scss/eemsdelta/style-webshop-eemsdelta.scss
  src/sources/forus-webshop/scss/geertruidenberg/style-webshop-geertruidenberg.scss
  src/sources/forus-webshop/scss/general/style-webshop-general.scss
  src/sources/forus-webshop/scss/general/vars.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/style-webshop-goereeoverflakkee.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/vars.scss
  src/sources/forus-webshop/scss/hartvanwestbrabant/style-webshop-hartvanwestbrabant.scss
  src/sources/forus-webshop/scss/heumen/style-webshop-heumen.scss
  src/sources/forus-webshop/scss/kerstpakket/style-webshop-kerstpakket.scss
  src/sources/forus-webshop/scss/kerstpakket/vars.scss
  src/sources/forus-webshop/scss/noordoostpolder/components/_breadcrumbs.scss
  src/sources/forus-webshop/scss/noordoostpolder/style-webshop-noordoostpolder.scss
  src/sources/forus-webshop/scss/oostgelre/style-webshop-oostgelre.scss
  src/sources/forus-webshop/scss/potjeswijzer/components/_breadcrumbs.scss
  src/sources/forus-webshop/scss/potjeswijzer/style-webshop-potjeswijzer.scss
  src/sources/forus-webshop/scss/potjeswijzer/vars.scss
  src/sources/forus-webshop/scss/schagen/style-webshop-schagen.scss
  src/sources/forus-webshop/scss/vergoedingen/includes/fonts.scss
  src/sources/forus-webshop/scss/vergoedingen/style-webshop-vergoedingen.scss
  src/sources/forus-webshop/scss/vergoedingen/vars.scss
  src/sources/forus-webshop/scss/waalwijk/style-webshop-waalwijk.scss
  src/sources/forus-webshop/scss/wadenheuvel/style-webshop-wadenheuvel.scss
  src/sources/forus-webshop/scss/wadenheuvel/vars.scss
  src/sources/forus-webshop/scss/westerkwartier/components/_breadcrumbs.scss
  src/sources/forus-webshop/scss/westerkwartier/style-webshop-westerkwartier.scss
  src/sources/forus-webshop/scss/winterswijk/components/_breadcrumbs.scss
  src/sources/forus-webshop/scss/winterswijk/style-webshop-winterswijk.scss
Labels: priority: High

#3051 wcag make some organizations block text visible on mobile
  src/sources/forus-webshop/scss/_common/sections/blocks/block-organizations.scss
Labels: priority: High
