Repository teamforus/forus-frontend, pull requests merged in 2023-03, with the labels that each got.

#2523 Provider fund unsubscribe feature
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/Modals/ModalFundUnsubscribeComponent.js
  src/sources/forus-platform/js/angular-1/components/OrganizationFundsComponent.js
  src/sources/forus-platform/js/angular-1/components/ProviderFundsComponent.js
  src/sources/forus-platform/js/angular-1/components/ProviderSignUpComponent.js
  src/sources/forus-platform/js/angular-1/components/SponsorFundUnsubscriptionsComponent.js
  src/sources/forus-platform/js/angular-1/components/SponsorProviderOrganizationsComponent.js
  src/sources/forus-platform/js/angular-1/config/i18n.js
  src/sources/forus-platform/js/angular-1/directives/FundCardAvailableProviderDirective.js
  src/sources/forus-platform/js/angular-1/directives/FundCardInvitationProviderDirective.js
  src/sources/forus-platform/js/angular-1/directives/FundCardProviderCanJoinDirective.js
  src/sources/forus-platform/js/angular-1/directives/FundCardProviderDirective.js
  src/sources/forus-platform/js/angular-1/directives/ProviderAvailableFundsTableDirective.js
  src/sources/forus-platform/js/angular-1/directives/ProviderFundFiltersDirective.js
  src/sources/forus-platform/js/angular-1/directives/ProviderFundUnsubscriptionsTableDirective.js
  src/sources/forus-platform/js/angular-1/directives/ProviderFundsCanJoinDirective.js
  src/sources/forus-platform/js/angular-1/directives/ProviderFundsInvitationTableDirective.js
  src/sources/forus-platform/js/angular-1/directives/ProviderFundsTableDirective.js
  src/sources/forus-platform/js/angular-1/directives/TableCheckboxControlDirective.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/i18n/nl/modals/danger-zone/cancel-provider-unsubscription.js
  src/sources/forus-platform/js/angular-1/i18n/nl/modals/danger-zone/remove-provider-application.js
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/fund-unsubscriptions.pug.i18n.js
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/provider-funds.pug.i18n.js
  src/sources/forus-platform/js/angular-1/routers/modals.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/js/angular-1/services/FundProviderInvitationsService.js
  src/sources/forus-platform/js/angular-1/services/FundUnsubscribeService.js
  src/sources/forus-platform/js/angular-1/services/ProviderFundService.js
  src/sources/forus-platform/pug/tpl/directives/fund-card-available-provider.pug
  src/sources/forus-platform/pug/tpl/directives/fund-card-invitation-provider.pug
  src/sources/forus-platform/pug/tpl/directives/fund-card-provider-can-join.pug
  src/sources/forus-platform/pug/tpl/directives/fund-card-provider.pug
  src/sources/forus-platform/pug/tpl/directives/provider-available-funds-table.pug
  src/sources/forus-platform/pug/tpl/directives/provider-fund-unsubscriptions-table.pug
  src/sources/forus-platform/pug/tpl/directives/provider-funds-can-join.pug
  src/sources/forus-platform/pug/tpl/directives/provider-funds-invitation-table.pug
  src/sources/forus-platform/pug/tpl/directives/provider-funds-table.pug
  src/sources/forus-platform/pug/tpl/directives/provider-signup-fund-card.pug
  src/sources/forus-platform/pug/tpl/directives/table-checkbox-control.pug
  src/sources/forus-platform/pug/tpl/modals/modal-fund-unsubscribe.pug
  src/sources/forus-platform/pug/tpl/pages/provider-funds.pug
  src/sources/forus-platform/pug/tpl/pages/provider-sign-up.pug
  src/sources/forus-platform/pug/tpl/pages/sponsor-fund-unsubscriptions.pug
  src/sources/forus-platform/pug/tpl/pages/sponsor-provider-organizations.pug
  src/sources/forus-platform/scss/_common/components/forms.scss
  src/sources/forus-platform/scss/_common/components/tables.scss
  src/sources/forus-platform/scss/_common/dashboard.scss
  src/sources/forus-webshop/scss/_common/components/_ui-controls.scss
Labels: priority: High

#2443 Update filters in provider dashboard funds page
  src/sources/forus-platform/js/angular-1/components/ProviderFundsComponent.js
  src/sources/forus-platform/js/angular-1/components/ProviderSignUpComponent.js
  src/sources/forus-platform/js/angular-1/directives/FundCardAvailableProviderDirective.js
  src/sources/forus-platform/js/angular-1/directives/FundCardInvitationProviderDirective.js
  src/sources/forus-platform/js/angular-1/directives/FundCardProviderDirective.js
  src/sources/forus-platform/js/angular-1/directives/ProviderFundFiltersDirective.js
  src/sources/forus-platform/pug/tpl/pages/provider-funds.pug
  src/sources/forus-platform/pug/tpl/pages/provider-sign-up.pug
Labels: priority: Medium

#2550 Add product reservations export
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/ReservationsComponent.js
  src/sources/forus-platform/js/angular-1/services/ProductReservationService.js
  src/sources/forus-platform/js/angular-1/services/ProductReservationsExportService.js
  src/sources/forus-platform/pug/tpl/pages/reservations.pug
Labels: priority: Low

#2535 Add sorting for the fund topups
  src/sources/forus-platform/pug/tpl/pages/organization-funds.pug
Labels: priority: Low

#2533 add flag for displaying the sponsor logo on the webshop
  src/qdt-env.sample.js
  src/sources/forus-webshop/pug/tpl/directives/app-footer.pug
  src/sources/forus-webshop/resources/webshop-groningen/assets/img/logo-footer.png
  src/sources/forus-webshop/scss/_common/layout/_footer.scss
Labels: priority: Medium

#2529 transaction overview page update bulk detail texts
  src/sources/forus-platform/pug/tpl/pages/transactions.pug
Labels: priority: Low

#2504 add delayed filters to paginator directive from the webshop
  src/sources/forus-platform/js/angular-1/directives/paginators/PaginatorDirective.js
  src/sources/forus-platform/pug/tpl/pages/fund-provider.pug
  src/sources/forus-platform/pug/tpl/pages/organization-funds.pug
  src/sources/forus-platform/pug/tpl/pages/product-vouchers.pug
  src/sources/forus-platform/pug/tpl/pages/reimbursements.pug
  src/sources/forus-platform/pug/tpl/pages/sponsor-provider-organization.pug
  src/sources/forus-platform/pug/tpl/pages/sponsor-provider-organizations.pug
  src/sources/forus-platform/pug/tpl/pages/transactions.pug
  src/sources/forus-platform/pug/tpl/pages/vouchers.pug
  src/sources/forus-webshop/js/angular-1/directives/paginators/PaginatorDirective.js
  src/sources/forus-webshop/pug/tpl/pages/funds.pug
  src/sources/forus-webshop/pug/tpl/pages/products.pug
  src/sources/forus-webshop/pug/tpl/pages/providers.pug
Labels: priority: Low

#2503 display total amount on product voucher details page
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/vouchers.pug.i18n.js
  src/sources/forus-platform/pug/tpl/pages/vouchers-show.pug
Labels: priority: Low

#2495 add has products filter for fund providers
  src/sources/forus-platform/js/angular-1/components/SponsorProviderOrganizationsComponent.js
  src/sources/forus-platform/pug/tpl/pages/sponsor-provider-organizations.pug
Labels: priority: Low

#2508 add auto tests for reimbursements
  src/sources/forus-platform/pug/tpl/directives/fund-selector.pug
  src/sources/forus-platform/pug/tpl/directives/menu-sponsor.pug
  src/sources/forus-platform/pug/tpl/modals/reimbursements/modal-reimbursement-resolve.pug
  src/sources/forus-platform/pug/tpl/pages/fund-requests.pug
  src/sources/forus-platform/pug/tpl/pages/reimbursements-show.pug
  src/sources/forus-platform/pug/tpl/pages/reimbursements.pug
Labels: priority: Low

#2539 Implementation pages add default description combine settings
  src/sources/forus-platform/js/angular-1/components/ImplementationCmsPageEditComponent.js
  src/sources/forus-platform/pug/tpl/pages/implementation-cms-page-edit.pug
  src/sources/forus-webshop/pug/tpl/pages/accessibility.pug
  src/sources/forus-webshop/pug/tpl/pages/explanation.pug
  src/sources/forus-webshop/pug/tpl/pages/privacy.pug
  src/sources/forus-webshop/pug/tpl/pages/sign-up-provider.pug
  src/sources/forus-webshop/scss/_common/includes/common.scss
Labels: priority: Medium

#2551 Updated Information About Us Page
  src/sources/forus-platform/pug/tpl/pages/website/current.pug
Labels: priority: Low

#2583 markdown editor edit raw feature
  src/sources/forus-platform/js/angular-1/directives/MarkdownDirective.js
  src/sources/forus-platform/js/angular-1/services/MarkdownService.js
  src/sources/forus-platform/scss/_common/blocks/block-markdownable.scss
Labels: priority: Medium
