Repository teamforus/forus-frontend, pull requests merged in 2024-01, with the labels that each got.

#3174 restore missing fundsTitle dusk attribute
  src/sources/forus-platform/pug/tpl/pages/organization-funds.pug
Labels: priority: High

#3119 Feature fund pre-checks
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/FundPreCheckComponent.js
  src/sources/forus-platform/js/angular-1/directives/FundPreCheckStepEditorDirective.js
  src/sources/forus-platform/js/angular-1/directives/blocks/BlockEmptyDirective.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/js/angular-1/services/ImplementationService.js
  src/sources/forus-platform/js/angular-1/services/PreCheckService.js
  src/sources/forus-platform/pug/tpl/directives/blocks/block-empty.pug
  src/sources/forus-platform/pug/tpl/directives/fund-pre-check-step-editor.pug
  src/sources/forus-platform/pug/tpl/directives/menu-sponsor.pug
  src/sources/forus-platform/pug/tpl/pages/fund-pre-check.pug
  src/sources/forus-platform/resources/_platform-common/assets/img/icon-drag.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/menu/icon-pre-check-active.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/menu/icon-pre-check-hover.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/menu/icon-pre-check.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/no-funds-icon.svg
  src/sources/forus-platform/scss/_common/blocks/block-pre-checks-blocks-editor.scss
  src/sources/forus-platform/scss/_common/dashboard.scss
  src/sources/forus-webshop/js/angular-1/angular-app.js
  src/sources/forus-webshop/js/angular-1/components/FundPreCheckComponent.js
  src/sources/forus-webshop/js/angular-1/components/FundRequestComponent.js
  src/sources/forus-webshop/js/angular-1/directives/ProgressPie.js
  src/sources/forus-webshop/js/angular-1/directives/lists/FundItemPreCheckDirective.js
  src/sources/forus-webshop/js/angular-1/modules/ui-controls/directives/templates/ui-control-date.pug
  src/sources/forus-webshop/js/angular-1/routers/router.js
  src/sources/forus-webshop/js/angular-1/services/FundService.js
  src/sources/forus-webshop/js/angular-1/services/PreCheckService.js
  src/sources/forus-webshop/pug/tpl/directives/lists/funds/fund-item-pre-check.pug
  src/sources/forus-webshop/pug/tpl/pages/fund-pre-check.pug
  src/sources/forus-webshop/pug/tpl/pages/funds.pug
  src/sources/forus-webshop/pug/tpl/pages/home.pug
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-pre-check-totals-active.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-pre-check-totals-inactive.svg
  src/sources/forus-webshop/scss/_common/sections/blocks/block-fund-pre-check-result.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-fund-pre-check.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-pre-check-banner.scss
  src/sources/forus-webshop/scss/_common/webshop.scss
Labels: priority: Medium

#3188 add implementation select for fund pre-check
  src/sources/forus-platform/js/angular-1/components/FundPreCheckComponent.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/pug/tpl/pages/fund-pre-check.pug
Labels: priority: Low

#3189 fix fund name overlap in provider fund tables
  src/sources/forus-platform/pug/tpl/directives/provider-available-funds-table.pug
  src/sources/forus-platform/pug/tpl/directives/provider-fund-unsubscriptions-table.pug
  src/sources/forus-platform/pug/tpl/directives/provider-funds-invitation-table.pug
  src/sources/forus-platform/pug/tpl/directives/provider-funds-table.pug
  src/sources/forus-platform/pug/tpl/directives/reservation-extra-payment-refunds.pug
  src/sources/forus-platform/pug/tpl/pages/sponsor-fund-unsubscriptions.pug
  src/sources/forus-platform/scss/_common/components/tables.scss
  src/sources/forus-platform/scss/_common/dashboard.scss
Labels: priority: Low

#3171 keep focus on generic search input
  src/sources/forus-webshop/js/angular-1/components/SearchResultComponent.js
  src/sources/forus-webshop/pug/tpl/directives/top-navbar-search.pug
Labels: priority: Medium

#3187 products and actions list refactoring
  src/sources/forus-webshop/js/angular-1/directives/BlockProductsDirective.js
  src/sources/forus-webshop/js/angular-1/directives/ProductsListDirective.js
  src/sources/forus-webshop/js/angular-1/directives/lists/ProductItemDirective.js
  src/sources/forus-webshop/pug/tpl/directives/block-products.pug
  src/sources/forus-webshop/pug/tpl/directives/lists/products/product-item-grid.pug
  src/sources/forus-webshop/pug/tpl/directives/lists/products/product-item-list.pug
  src/sources/forus-webshop/pug/tpl/pages/home.pug
  src/sources/forus-webshop/scss/_common/components/card.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-bookmark-toggle.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-organizations.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-products-list.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-products.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-subsidies-list.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-subsidies.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/funds.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/products.scss
  src/sources/forus-webshop/scss/_common/sections/products.scss
  src/sources/forus-webshop/scss/_common/webshop.scss
  src/sources/forus-webshop/scss/berkelland/sections/blocks/products.scss
  src/sources/forus-webshop/scss/doetegoed/sections/blocks/products.scss
  src/sources/forus-webshop/scss/doetegoed/style-webshop-doetegoed.scss
  src/sources/forus-webshop/scss/general/vars.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/sections/blocks/block-products-list.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/sections/blocks/block-products.scss
  src/sources/forus-webshop/scss/goereeoverflakkee/style-webshop-goereeoverflakkee.scss
  src/sources/forus-webshop/scss/groningen/sections/blocks/products.scss
  src/sources/forus-webshop/scss/groningen/style-webshop-groningen.scss
  src/sources/forus-webshop/scss/noordoostpolder/sections/blocks/products.scss
  src/sources/forus-webshop/scss/noordoostpolder/style-webshop-noordoostpolder.scss
  src/sources/forus-webshop/scss/oostgelre/sections/blocks/products.scss
  src/sources/forus-webshop/scss/schagen/includes/shame.scss
  src/sources/forus-webshop/scss/vergoedingen/includes/shame.scss
  src/sources/forus-webshop/scss/winterswijk/sections/blocks/products.scss
Labels: priority: Medium

#3168 fix the cancel button on the reservation confirmation step
  src/sources/forus-webshop/pug/tpl/modals/modal-product-reserve.pug
Labels: priority: Medium

#3169 fix overlapping product names on reservation list page
  src/sources/forus-webshop/pug/tpl/directives/reservation-card.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-reservations.scss
Labels: priority: Medium

#3155 Add cancel pending and accepted reservations by requester through modal
  src/sources/forus-webshop/js/angular-1/i18n/nl/modals/modal-product-reserve-cancel.js
  src/sources/forus-webshop/pug/tpl/directives/reservation-card.pug
  src/sources/forus-webshop/pug/tpl/modals/modal-product-reserve-cancel.pug
  src/sources/forus-webshop/pug/tpl/pages/reservation-show.pug
Labels: priority: Medium

#3144 Pin code modal styles update
  src/sources/forus-platform/pug/tpl/modals/modal-pin-code.pug
  src/sources/forus-platform/resources/_platform-common/assets/img/Base7.png
  src/sources/forus-platform/resources/_platform-common/assets/img/icon-auth/download-me-app.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/icon-auth/icon-app-step-separator.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/icon-auth/me-app-fill-pin-code.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/icon-auth/pair-me-app.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/line1.png
  src/sources/forus-platform/resources/_platform-common/assets/img/screen1.png
  src/sources/forus-platform/resources/_platform-common/assets/img/screen2.png
  src/sources/forus-platform/scss/_common/dashboard.scss
  src/sources/forus-platform/scss/_common/modals/modal-pin-code.scss
  src/sources/forus-webshop/js/angular-1/components/Modals/ModalOpenInMeComponent.js
  src/sources/forus-webshop/pug/tpl/modals/modal-open-in-me.pug
  src/sources/forus-webshop/pug/tpl/modals/modal-pin-code.pug
  src/sources/forus-webshop/resources/_webshop-common/assets/img/Base7.png
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-auth/download-me-app.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-auth/icon-app-step-separator-mobile.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-auth/icon-app-step-separator.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-auth/me-app-fill-pin-code.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/icon-auth/pair-me-app.svg
  src/sources/forus-webshop/resources/_webshop-common/assets/img/line1.png
  src/sources/forus-webshop/resources/_webshop-common/assets/img/screen1.png
  src/sources/forus-webshop/resources/_webshop-common/assets/img/screen2.png
  src/sources/forus-webshop/scss/_common/components/_modals.scss
  src/sources/forus-webshop/scss/_common/includes/shame.scss
  src/sources/forus-webshop/scss/_common/modals/modal-pin-code.scss
  src/sources/forus-webshop/scss/_common/webshop.scss
Labels: priority: Low

#3154 Add hover effect for product and provider name in reservations
  src/sources/forus-webshop/scss/_common/sections/blocks/block-reservations.scss
Labels: priority: Medium

#3190 Restore provider unsubscriptions block on the sponsor provider organi…
  src/sources/forus-platform/pug/tpl/pages/sponsor-provider-organizations.pug
  src/sources/forus-platform/scss/_common/dashboard.scss
Labels: priority: Medium

#3164 add implementation column to several dashboard tables
  src/sources/forus-platform/js/angular-1/components/OrganizationFundsComponent.js
  src/sources/forus-platform/js/angular-1/components/ReimbursementsComponent.js
  src/sources/forus-platform/js/angular-1/components/SponsorProviderOrganizationsComponent.js
  src/sources/forus-platform/js/angular-1/directives/ProviderAvailableFundsTableDirective.js
  src/sources/forus-platform/js/angular-1/i18n/nl/components/organization-funds.js
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/provider-funds.pug.i18n.js
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/reimbursements.pug.i18n.js
  src/sources/forus-platform/js/angular-1/modules/select-control/directives/SelectControlDirective.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/pug/tpl/directives/provider-available-funds-table.pug
  src/sources/forus-platform/pug/tpl/directives/provider-fund-unsubscriptions-table.pug
  src/sources/forus-platform/pug/tpl/directives/provider-funds-invitation-table.pug
  src/sources/forus-platform/pug/tpl/directives/provider-funds-table.pug
  src/sources/forus-platform/pug/tpl/pages/organization-funds.pug
  src/sources/forus-platform/pug/tpl/pages/reimbursements.pug
  src/sources/forus-platform/pug/tpl/pages/sponsor-provider-organizations.pug
  src/sources/forus-platform/scss/_common/components/tables.scss
  src/sources/forus-webshop/js/angular-1/modules/select-control/directives/SelectControlDirective.js
Labels: priority: Medium

#3141 Hide the extra payment column in reservations if provider not accepted for Mollie
  src/sources/forus-platform/js/angular-1/components/ReservationsComponent.js
  src/sources/forus-platform/pug/tpl/pages/reservations.pug
Labels: priority: Medium

#3140 Show extra payment config for provider if mollie onboarding complete
  src/sources/forus-platform/pug/tpl/pages/products-edit.pug
  src/sources/forus-platform/pug/tpl/pages/reservations-settings.pug
Labels: priority: Low

#3147 Check extra payment refund state when accept or reject reservation
  src/sources/forus-platform/js/angular-1/components/ReservationShowComponent.js
  src/sources/forus-platform/js/angular-1/components/ReservationsComponent.js
  src/sources/forus-platform/js/angular-1/services/ProductReservationService.js
  src/sources/forus-platform/pug/tpl/directives/reservation-extra-payment-details.pug
  src/sources/forus-platform/pug/tpl/pages/reservation-show.pug
  src/sources/forus-platform/pug/tpl/pages/reservations.pug
Labels: priority: Medium

#3135 Add reservation fields enabled to product
  src/sources/forus-platform/js/angular-1/components/ProductsEditComponent.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/services/ProductService.js
  src/sources/forus-platform/pug/tpl/pages/products-edit.pug
Labels: priority: Low

#3198 Add select payment profile for mollie
  src/sources/forus-platform/js/angular-1/components/PaymentMethodsComponent.js
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/mollie-connection.pug.i18n.js
  src/sources/forus-platform/js/angular-1/services/MollieConnectionService.js
  src/sources/forus-platform/pug/tpl/pages/payment-methods.pug
Labels: priority: Medium

#3142 Add filter providers by extra payments allowed by sponsor
  src/sources/forus-platform/js/angular-1/components/SponsorProviderOrganizationsComponent.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/pug/tpl/pages/sponsor-provider-organizations.pug
Labels: priority: Low

#3208 Pre-check enhancements and fixes
  src/sources/forus-platform/js/angular-1/components/FundPreCheckComponent.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/pug/tpl/directives/fund-pre-check-step-editor.pug
  src/sources/forus-platform/pug/tpl/pages/fund-pre-check.pug
  src/sources/forus-webshop/js/angular-1/components/FundPreCheckComponent.js
  src/sources/forus-webshop/js/angular-1/directives/lists/FundItemPreCheckDirective.js
  src/sources/forus-webshop/pug/tpl/directives/lists/funds/fund-item-pre-check.pug
  src/sources/forus-webshop/pug/tpl/pages/fund-pre-check.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-fund-pre-check-result.scss
Labels: priority: High

#3209 Pre-check external funds application adjustments
  src/sources/forus-webshop/pug/tpl/directives/lists/funds/fund-item-pre-check.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-fund-pre-check-result.scss
Labels: priority: High

#3213 Marketplace text changes
  src/sources/forus-platform/js/angular-1/services/FeaturesService.js
  src/sources/forus-platform/pug/tpl/pages/features.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-auth-2-fa.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-backoffice-api.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-bi-tools.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-bng.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-digid.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-email-connection.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-iconnect-api.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-physical-cards.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-reimbursements.pug
Labels: priority: Medium
