Repository teamforus/forus-frontend, pull requests merged in 2024-02, with the labels that each got.

#3185 Fix url for provider cms page in fund list provider can join
  src/sources/forus-platform/pug/tpl/directives/provider-funds-can-join.pug
Labels: priority: Medium

#3226 Fix criterion control type in fund requests
  src/sources/forus-webshop/js/angular-1/services/FundService.js
Labels: priority: Medium

#3225 Hide 'per gezin' and 'per kid' on the pre-check totals page
  src/sources/forus-webshop/pug/tpl/directives/lists/funds/fund-item-pre-check.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-fund-pre-check-result.scss
Labels: priority: High

#3221 Add new pages to features marketplace
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/directives/blocks/BlockAdditionalFeaturesDirective.js
  src/sources/forus-platform/js/angular-1/services/FeaturesService.js
  src/sources/forus-platform/pug/tpl/directives/blocks/block-additional-features.pug
  src/sources/forus-platform/pug/tpl/directives/blocks/block-feature.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-auth-2-fa.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-backoffice-api.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-bi-tools.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-bng.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-digid.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-email-connection.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-extra-payments.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-fund-requests.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-iconnect-api.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-physical-cards.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-reimbursements.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-voucher-records.pug
  src/sources/forus-platform/resources/_platform-common/assets/img/features/icons/extra-payments/icon-1.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/icons/extra-payments/icon-2.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/icons/extra-payments/icon-3.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/icons/extra-payments/icon-4.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/icons/extra_payments.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/icons/fund-requests/icon-1.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/icons/fund-requests/icon-2.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/icons/fund-requests/icon-3.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/icons/fund-requests/icon-4.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/icons/fund_requests.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/icons/voucher-records/icon-1.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/icons/voucher-records/icon-2.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/icons/voucher-records/icon-3.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/icons/voucher-records/icon-4.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/icons/voucher-records/icon-step-1.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/icons/voucher-records/icon-step-2.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/icons/voucher-records/icon-step-3.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/icons/voucher-records/icon-step-4.svg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/img/extra-payments/banner-action-bg.jpg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/img/extra-payments/banner.jpg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/img/extra-payments/image-text-block.jpg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/img/fund-requests/banner-action-bg.jpg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/img/fund-requests/banner.jpg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/img/voucher-records/banner-action-bg.jpg
  src/sources/forus-platform/resources/_platform-common/assets/img/features/img/voucher-records/banner.jpg
  src/sources/forus-platform/scss/_common/blocks/marketplace-features/block-feature-list.scss
  src/sources/forus-platform/scss/_common/blocks/marketplace-features/block-feature-text-image-columns.scss
  src/sources/forus-platform/scss/_common/blocks/marketplace-features/block-feature.scss
Labels: priority: High

#3223 react provider dashboard update
  src/sources/forus-platform/js/angular-1/components/Modals/ModalReservationUploadComponent.js
  src/sources/forus-platform/js/angular-1/components/ProviderSignUpComponent.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/pug/tpl/pages/offices.pug
  src/sources/forus-platform/pug/tpl/pages/products-edit.pug
  src/sources/forus-platform/pug/tpl/pages/products-show.pug
  src/sources/forus-platform/pug/tpl/pages/products.pug
  src/sources/forus-platform/pug/tpl/pages/provider-overview.pug
  src/sources/forus-platform/pug/tpl/pages/transactions.pug
  src/sources/forus-platform/scss/_common/blocks/block-danger_zone.scss
  src/sources/forus-platform/scss/_common/components/forms.scss
  src/sources/forus-platform/scss/_common/components/modals.scss
  src/sources/forus-platform/scss/_common/dashboard.scss
  src/sources/forus-platform/scss/_common/includes/third-party.scss
  src/sources/forus-webshop/js/angular-1/directives/ProvidersMapDirective.js
  src/sources/forus-webshop/scss/_common/sections/blocks/block-sign_up.scss
Labels: priority: High

#3204 Add 2fa phone masking
  src/sources/forus-platform/js/angular-1/components/Security2FAComponent.js
  src/sources/forus-platform/pug/tpl/pages/security/2fa.pug
  src/sources/forus-platform/scss/_common/blocks/block-auth-2fa.scss
  src/sources/forus-webshop/js/angular-1/components/Security2FAComponent.js
  src/sources/forus-webshop/pug/tpl/pages/security/2fa.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-auth-2fa.scss
Labels: priority: Medium

#3224 add extra payment details on the webshop reservation details page
  src/sources/forus-webshop/js/angular-1/components/ReservationShowComponent.js
  src/sources/forus-webshop/pug/tpl/pages/reservation-show.pug
  src/sources/forus-webshop/scss/_common/components/_label.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-card-table.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-key-value-list.scss
  src/sources/forus-webshop/scss/_common/sections/blocks/block-reservation.scss
  src/sources/forus-webshop/scss/_common/webshop.scss
Labels: priority: Medium

#3199 Add created at in reservation list on webshop
  src/sources/forus-webshop/js/angular-1/i18n/nl/directives/reservation-card.js
  src/sources/forus-webshop/pug/tpl/directives/reservation-card.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-reservations.scss
  src/sources/forus-webshop/scss/doetegoed/style-webshop-doetegoed.scss
Labels: priority: Medium

#3219 add filter for expired product reservations
  src/sources/forus-platform/js/angular-1/components/ReservationsComponent.js
  src/sources/forus-platform/pug/tpl/pages/reservations.pug
Labels: priority: Medium

#3239 Feature.text changes
  src/sources/forus-platform/pug/tpl/pages/features.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-fund-requests.pug
  src/sources/forus-platform/pug/tpl/pages/features/feature-physical-cards.pug
Labels: priority: High

#3238 Add pseudo redirect links for feature pages
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/FeatureRedirectComponent.js
  src/sources/forus-platform/js/angular-1/components/FeaturesRedirectComponent.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/pug/tpl/directives/menu-sponsor.pug
Labels: priority: High

#3232 add per page selector for sponsor dashboard tables
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/EventLogsComponent.js
  src/sources/forus-platform/js/angular-1/components/ExternalValidatorsComponent.js
  src/sources/forus-platform/js/angular-1/components/FinancialDashboardComponent.js
  src/sources/forus-platform/js/angular-1/components/FundsShowComponent.js
  src/sources/forus-platform/js/angular-1/components/OrganizationEmployeesComponent.js
  src/sources/forus-platform/js/angular-1/components/OrganizationFundsComponent.js
  src/sources/forus-platform/js/angular-1/components/ProductVouchersComponent.js
  src/sources/forus-platform/js/angular-1/components/ReimbursementsComponent.js
  src/sources/forus-platform/js/angular-1/components/ReservationExtraPaymentsComponent.js
  src/sources/forus-platform/js/angular-1/components/SponsorProviderOrganizationsComponent.js
  src/sources/forus-platform/js/angular-1/components/TransactionsComponent.js
  src/sources/forus-platform/js/angular-1/components/VouchersComponent.js
  src/sources/forus-platform/js/angular-1/directives/EventLogsDirective.js
  src/sources/forus-platform/js/angular-1/directives/PrevalidatedTableDirective.js
  src/sources/forus-platform/js/angular-1/directives/VoucherTransactionsDirective.js
  src/sources/forus-platform/js/angular-1/directives/paginators/PaginatorDirective.js
  src/sources/forus-platform/js/angular-1/i18n/i18n-nl.js
  src/sources/forus-platform/js/angular-1/routers/router.js
  src/sources/forus-platform/js/angular-1/services/LocalStorageService.js
  src/sources/forus-platform/js/angular-1/services/PaginatorService.js
  src/sources/forus-platform/pug/tpl/directives/event-logs.pug
  src/sources/forus-platform/pug/tpl/directives/paginators/paginator.pug
  src/sources/forus-platform/pug/tpl/directives/prevalidated-table.pug
  src/sources/forus-platform/pug/tpl/directives/voucher-transactions.pug
  src/sources/forus-platform/pug/tpl/pages/event-logs.pug
  src/sources/forus-platform/pug/tpl/pages/external-validators.pug
  src/sources/forus-platform/pug/tpl/pages/financial-dashboard.pug
  src/sources/forus-platform/pug/tpl/pages/funds-show.pug
  src/sources/forus-platform/pug/tpl/pages/organization-employees.pug
  src/sources/forus-platform/pug/tpl/pages/organization-funds.pug
  src/sources/forus-platform/pug/tpl/pages/product-vouchers.pug
  src/sources/forus-platform/pug/tpl/pages/reimbursements.pug
  src/sources/forus-platform/pug/tpl/pages/reservation-extra-payments.pug
  src/sources/forus-platform/pug/tpl/pages/sponsor-provider-organizations.pug
  src/sources/forus-platform/pug/tpl/pages/transactions.pug
  src/sources/forus-platform/pug/tpl/pages/vouchers-show.pug
  src/sources/forus-platform/pug/tpl/pages/vouchers.pug
  src/sources/forus-platform/scss/_common/components/tables.scss
Labels: priority: Low

#3218 add pdf download for pre-check results
  src/sources/forus-webshop/js/angular-1/components/FundPreCheckComponent.js
  src/sources/forus-webshop/js/angular-1/services/PreCheckService.js
  src/sources/forus-webshop/pug/tpl/pages/fund-pre-check.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-fund-pre-check.scss
Labels: priority: High

#3186 add table column tooltips
  src/sources/forus-platform/js/angular-1/angular-app.js
  src/sources/forus-platform/js/angular-1/components/VouchersComponent.js
  src/sources/forus-platform/js/angular-1/directives/ToastsRootDirective.js
  src/sources/forus-platform/js/angular-1/directives/table/TableConfigDirective.js
  src/sources/forus-platform/js/angular-1/directives/table/table-config.pug
  src/sources/forus-platform/js/angular-1/i18n/nl/pages/vouchers.pug.i18n.js
  src/sources/forus-platform/js/angular-1/services/ToastService.js
  src/sources/forus-platform/js/angular-1/services/VoucherService.js
  src/sources/forus-platform/pug/index.pug
  src/sources/forus-platform/pug/tpl/directives/toast.pug
  src/sources/forus-platform/pug/tpl/pages/product-vouchers.pug
  src/sources/forus-platform/pug/tpl/pages/vouchers-show.pug
  src/sources/forus-platform/pug/tpl/pages/vouchers.pug
  src/sources/forus-platform/scss/_common/blocks/block-table-config.scss
  src/sources/forus-platform/scss/_common/blocks/block-toast.scss
  src/sources/forus-platform/scss/_common/components/tables.scss
  src/sources/forus-platform/scss/_common/dashboard.scss
  src/sources/forus-platform/scss/_common/includes/helpers.scss
Labels: priority: Medium

#3254 add website news page
  src/sources/forus-platform/js/angular-1/angular-app-website.js
  src/sources/forus-platform/js/angular-1/components/website/NewsComponent.js
  src/sources/forus-platform/js/angular-1/routers/landing/router.js
  src/sources/forus-platform/pug/tpl/directives/website/navbar.pug
  src/sources/forus-platform/pug/tpl/pages/website/home.pug
  src/sources/forus-platform/pug/tpl/pages/website/news.pug
  src/sources/forus-platform/resources/platform-general/assets/img/website/news-banner.jpg
  src/sources/forus-platform/resources/platform-general/assets/img/website/news-our-goals.jpg
  src/sources/forus-platform/resources/platform-general/assets/img/website/news-planning.jpg
  src/sources/forus-platform/resources/platform-general/assets/img/website/wave.svg
  src/sources/forus-platform/scss/general/website/components/content-area.scss
  src/sources/forus-platform/scss/general/website/layout/_header.scss
  src/sources/forus-platform/scss/general/website/sections/news.scss
  src/sources/forus-platform/scss/general/website/style.scss
Labels: priority: High

#3243 Implement pre-check knock-out criteria
  src/sources/forus-platform/js/angular-1/components/FundPreCheckComponent.js
  src/sources/forus-platform/pug/tpl/directives/fund-pre-check-step-editor.pug
  src/sources/forus-platform/scss/_common/blocks/block-pre-checks-blocks-editor.scss
  src/sources/forus-platform/scss/_common/includes/helpers.scss
  src/sources/forus-webshop/js/angular-1/directives/lists/FundItemPreCheckDirective.js
  src/sources/forus-webshop/pug/tpl/directives/lists/funds/fund-item-pre-check.pug
  src/sources/forus-webshop/scss/_common/sections/blocks/block-fund-pre-check-result.scss
Labels: priority: High

#3249 Fix event logs search for employees relation
  src/sources/forus-platform/js/angular-1/components/EventLogsComponent.js
  src/sources/forus-platform/js/angular-1/directives/EventLogsDirective.js
Labels: priority: Medium, scope: tiny

#3259 Website news page style adjustments
  src/sources/forus-platform/pug/tpl/directives/website/navbar.pug
  src/sources/forus-platform/resources/platform-general/assets/img/header-home2.png
  src/sources/forus-platform/resources/platform-general/assets/img/website/news-banner-mobile-homepage.jpg
  src/sources/forus-platform/resources/platform-general/assets/img/website/news-banner-mobile.jpg
  src/sources/forus-platform/scss/general/website/layout/_header.scss
  src/sources/forus-platform/scss/general/website/sections/news.scss
Labels: priority: Medium
